//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for addlPersonnelsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addlPersonnelsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AddlPersonnel" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="add_per_contact_name" type="{}string60"/>
 *                   &lt;element name="add_per_email_address" type="{}emailAddrType" minOccurs="0"/>
 *                   &lt;element name="add_per_pos_title" type="{}string70" minOccurs="0"/>
 *                   &lt;element name="add_per_phone_number" type="{}string15" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addlPersonnelsType", propOrder = {
    "addlPersonnel"
})
public class AddlPersonnelsType {

    @XmlElement(name = "AddlPersonnel", required = true)
    protected List<AddlPersonnel> addlPersonnel;

    /**
     * Gets the value of the addlPersonnel property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addlPersonnel property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddlPersonnel().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddlPersonnelsType.AddlPersonnel }
     *
     *
     */
    public List<AddlPersonnel> getAddlPersonnel() {
        if (addlPersonnel == null) {
            addlPersonnel = new ArrayList<AddlPersonnel>();
        }
        return this.addlPersonnel;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="add_per_contact_name" type="{}string60"/>
     *         &lt;element name="add_per_email_address" type="{}emailAddrType" minOccurs="0"/>
     *         &lt;element name="add_per_pos_title" type="{}string70" minOccurs="0"/>
     *         &lt;element name="add_per_phone_number" type="{}string15" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "addPerContactName",
        "addPerEmailAddress",
        "addPerPosTitle",
        "addPerPhoneNumber"
    })
    public static class AddlPersonnel {

        @XmlElement(name = "add_per_contact_name", required = true)
        protected String addPerContactName;
        @XmlElement(name = "add_per_email_address")
        protected String addPerEmailAddress;
        @XmlElement(name = "add_per_pos_title")
        protected String addPerPosTitle;
        @XmlElement(name = "add_per_phone_number")
        protected String addPerPhoneNumber;

        /**
         * Gets the value of the addPerContactName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddPerContactName() {
            return addPerContactName;
        }

        /**
         * Sets the value of the addPerContactName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddPerContactName(String value) {
            this.addPerContactName = value;
        }

        /**
         * Gets the value of the addPerEmailAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddPerEmailAddress() {
            return addPerEmailAddress;
        }

        /**
         * Sets the value of the addPerEmailAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddPerEmailAddress(String value) {
            this.addPerEmailAddress = value;
        }

        /**
         * Gets the value of the addPerPosTitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddPerPosTitle() {
            return addPerPosTitle;
        }

        /**
         * Sets the value of the addPerPosTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddPerPosTitle(String value) {
            this.addPerPosTitle = value;
        }

        /**
         * Gets the value of the addPerPhoneNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddPerPhoneNumber() {
            return addPerPhoneNumber;
        }

        /**
         * Sets the value of the addPerPhoneNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddPerPhoneNumber(String value) {
            this.addPerPhoneNumber = value;
        }

    }

}
