//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.27 at 01:18:06 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="addr_line" type="{}string70" maxOccurs="5" minOccurs="0"/>
 *         &lt;element name="city" type="{}string40" minOccurs="0"/>
 *         &lt;element name="zip" type="{}zipType" minOccurs="0"/>
 *         &lt;element name="zip4" type="{}zip4Type" minOccurs="0"/>
 *         &lt;element name="postal_code_prefix" type="{}string15" minOccurs="0"/>
 *         &lt;element name="postal_code_suffix" type="{}string15" minOccurs="0"/>
 *         &lt;element name="county" type="{}string20" minOccurs="0"/>
 *         &lt;element name="state" type="{}stateType" minOccurs="0"/>
 *         &lt;element name="country" type="{}countryType" minOccurs="0"/>
 *         &lt;element name="latitude" type="{}string40" minOccurs="0"/>
 *         &lt;element name="longitude" type="{}string40" minOccurs="0"/>
 *         &lt;element name="lat_lon_manual_update" type="{}string2" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Address_seq_num" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="inherited_address" type="{}yesNoFlag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addressType", propOrder = {
    "addrLine",
    "city",
    "zip",
    "zip4",
    "postalCodePrefix",
    "postalCodeSuffix",
    "county",
    "state",
    "country",
    "latitude",
    "longitude",
    "latLonManualUpdate"
})
public class AddressType {

    @XmlElement(name = "addr_line")
    protected List<String> addrLine;
    protected String city;
    protected String zip;
    protected String zip4;
    @XmlElement(name = "postal_code_prefix")
    protected String postalCodePrefix;
    @XmlElement(name = "postal_code_suffix")
    protected String postalCodeSuffix;
    protected String county;
    protected StateType state;
    protected CountryType country;
    protected String latitude;
    protected String longitude;
    @XmlElement(name = "lat_lon_manual_update")
    protected String latLonManualUpdate;
    @XmlAttribute(name = "Address_seq_num")
    protected BigInteger addressSeqNum;
    @XmlAttribute(name = "inherited_address")
    protected String inheritedAddress;

    /**
     * Gets the value of the addrLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addrLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddrLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAddrLine() {
        if (addrLine == null) {
            addrLine = new ArrayList<String>();
        }
        return this.addrLine;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the zip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZip() {
        return zip;
    }

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZip(String value) {
        this.zip = value;
    }

    /**
     * Gets the value of the zip4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZip4() {
        return zip4;
    }

    /**
     * Sets the value of the zip4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZip4(String value) {
        this.zip4 = value;
    }

    /**
     * Gets the value of the postalCodePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCodePrefix() {
        return postalCodePrefix;
    }

    /**
     * Sets the value of the postalCodePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCodePrefix(String value) {
        this.postalCodePrefix = value;
    }

    /**
     * Gets the value of the postalCodeSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCodeSuffix() {
        return postalCodeSuffix;
    }

    /**
     * Sets the value of the postalCodeSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCodeSuffix(String value) {
        this.postalCodeSuffix = value;
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCounty(String value) {
        this.county = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link StateType }
     *     
     */
    public StateType getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateType }
     *     
     */
    public void setState(StateType value) {
        this.state = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link CountryType }
     *     
     */
    public CountryType getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryType }
     *     
     */
    public void setCountry(CountryType value) {
        this.country = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatitude(String value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongitude(String value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the latLonManualUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatLonManualUpdate() {
        return latLonManualUpdate;
    }

    /**
     * Sets the value of the latLonManualUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatLonManualUpdate(String value) {
        this.latLonManualUpdate = value;
    }

    /**
     * Gets the value of the addressSeqNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAddressSeqNum() {
        return addressSeqNum;
    }

    /**
     * Sets the value of the addressSeqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAddressSeqNum(BigInteger value) {
        this.addressSeqNum = value;
    }

    /**
     * Gets the value of the inheritedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInheritedAddress() {
        return inheritedAddress;
    }

    /**
     * Sets the value of the inheritedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInheritedAddress(String value) {
        this.inheritedAddress = value;
    }

}
