//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for assocMemberIndType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assocMemberIndType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mem_first_name" type="{}firstNameType" minOccurs="0"/>
 *         &lt;element name="mem_last_name" type="{}lastNameType"/>
 *         &lt;element name="mem_middle_init_or_name" type="{}middleNameType" minOccurs="0"/>
 *         &lt;element name="mem_name_prefix" type="{}namePrefixType" minOccurs="0"/>
 *         &lt;element name="mem_name_suffix" type="{}nameSuffixType" minOccurs="0"/>
 *         &lt;element name="mem_prof_suffix" type="{}profSuffixType" minOccurs="0"/>
 *         &lt;element name="mem_ind_punctuated_name" type="{}indPunctuatedNameType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assocMemberIndType", propOrder = {
    "memFirstName",
    "memLastName",
    "memMiddleInitOrName",
    "memNamePrefix",
    "memNameSuffix",
    "memProfSuffix",
    "memIndPunctuatedName"
})
public class AssocMemberIndType {

    @XmlElement(name = "mem_first_name")
    protected String memFirstName;
    @XmlElement(name = "mem_last_name", required = true)
    protected String memLastName;
    @XmlElement(name = "mem_middle_init_or_name")
    protected String memMiddleInitOrName;
    @XmlElement(name = "mem_name_prefix")
    protected String memNamePrefix;
    @XmlElement(name = "mem_name_suffix")
    protected String memNameSuffix;
    @XmlElement(name = "mem_prof_suffix")
    protected String memProfSuffix;
    @XmlElement(name = "mem_ind_punctuated_name")
    protected String memIndPunctuatedName;

    /**
     * Gets the value of the memFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemFirstName() {
        return memFirstName;
    }

    /**
     * Sets the value of the memFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemFirstName(String value) {
        this.memFirstName = value;
    }

    /**
     * Gets the value of the memLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemLastName() {
        return memLastName;
    }

    /**
     * Sets the value of the memLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemLastName(String value) {
        this.memLastName = value;
    }

    /**
     * Gets the value of the memMiddleInitOrName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemMiddleInitOrName() {
        return memMiddleInitOrName;
    }

    /**
     * Sets the value of the memMiddleInitOrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemMiddleInitOrName(String value) {
        this.memMiddleInitOrName = value;
    }

    /**
     * Gets the value of the memNamePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemNamePrefix() {
        return memNamePrefix;
    }

    /**
     * Sets the value of the memNamePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemNamePrefix(String value) {
        this.memNamePrefix = value;
    }

    /**
     * Gets the value of the memNameSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemNameSuffix() {
        return memNameSuffix;
    }

    /**
     * Sets the value of the memNameSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemNameSuffix(String value) {
        this.memNameSuffix = value;
    }

    /**
     * Gets the value of the memProfSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemProfSuffix() {
        return memProfSuffix;
    }

    /**
     * Sets the value of the memProfSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemProfSuffix(String value) {
        this.memProfSuffix = value;
    }

    /**
     * Gets the value of the memIndPunctuatedName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemIndPunctuatedName() {
        return memIndPunctuatedName;
    }

    /**
     * Sets the value of the memIndPunctuatedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemIndPunctuatedName(String value) {
        this.memIndPunctuatedName = value;
    }

}
