//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for barAdmissionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="barAdmissionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bar_name" type="{}string70"/>
 *         &lt;element name="bar_year" type="{}digitYearType" minOccurs="0"/>
 *         &lt;element name="bar_license_number" type="{}string10" minOccurs="0"/>
 *         &lt;element name="bar_license_expire_year" type="{}digitYearType" minOccurs="0"/>
 *         &lt;element name="bar_id" type="{}string8" minOccurs="0"/>
 *         &lt;element name="bar_code" type="{}digit5"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "barAdmissionType", propOrder = {
    "barName",
    "barYear",
    "barLicenseNumber",
    "barLicenseExpireYear",
    "barId",
    "barCode"
})
public class BarAdmissionType {

    @XmlElement(name = "bar_name", required = true)
    protected String barName;
    @XmlElement(name = "bar_year")
    protected String barYear;
    @XmlElement(name = "bar_license_number")
    protected String barLicenseNumber;
    @XmlElement(name = "bar_license_expire_year")
    protected String barLicenseExpireYear;
    @XmlElement(name = "bar_id")
    protected String barId;
    @XmlElement(name = "bar_code", required = true)
    protected BigInteger barCode;

    /**
     * Gets the value of the barName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarName() {
        return barName;
    }

    /**
     * Sets the value of the barName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarName(String value) {
        this.barName = value;
    }

    /**
     * Gets the value of the barYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarYear() {
        return barYear;
    }

    /**
     * Sets the value of the barYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarYear(String value) {
        this.barYear = value;
    }

    /**
     * Gets the value of the barLicenseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarLicenseNumber() {
        return barLicenseNumber;
    }

    /**
     * Sets the value of the barLicenseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarLicenseNumber(String value) {
        this.barLicenseNumber = value;
    }

    /**
     * Gets the value of the barLicenseExpireYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarLicenseExpireYear() {
        return barLicenseExpireYear;
    }

    /**
     * Sets the value of the barLicenseExpireYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarLicenseExpireYear(String value) {
        this.barLicenseExpireYear = value;
    }

    /**
     * Gets the value of the barId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarId() {
        return barId;
    }

    /**
     * Sets the value of the barId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarId(String value) {
        this.barId = value;
    }

    /**
     * Gets the value of the barCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBarCode() {
        return barCode;
    }

    /**
     * Sets the value of the barCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBarCode(BigInteger value) {
        this.barCode = value;
    }

}
