//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for childrenAfflType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="childrenAfflType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChildAffl" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="child_first_name" type="{}firstNameType" minOccurs="0"/>
 *                   &lt;element name="child_last_name" type="{}lastNameType"/>
 *                   &lt;element name="child_middle_init_or_name" type="{}middleNameType" minOccurs="0"/>
 *                   &lt;element name="child_name_prefix" type="{}namePrefixType" minOccurs="0"/>
 *                   &lt;element name="child_name_suffix" type="{}nameSuffixType" minOccurs="0"/>
 *                   &lt;element name="child_prof_suffix" type="{}profSuffixType" minOccurs="0"/>
 *                   &lt;element name="child_ind_punctuated_name" type="{}indPunctuatedNameType" minOccurs="0"/>
 *                   &lt;element name="child_pos_title" type="{}string140" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="child_firmsite_url" type="{}string100" />
 *                 &lt;attribute name="child_guid" type="{}guidType" />
 *                 &lt;attribute name="child_of_branch_flag" type="{}yesNoFlag" />
 *                 &lt;attribute name="child_org_profile_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="child_org_wld_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="child_profession_code" type="{}professionCodeType" />
 *                 &lt;attribute name="child_profile_id" type="{}profileIdType" />
 *                 &lt;attribute name="child_status_code" type="{}statusCodeType" />
 *                 &lt;attribute name="child_wld_id" type="{}wldIdType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="user_defined_order" type="{}yesNoFlag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "childrenAfflType", propOrder = {
    "childAffl"
})
public class ChildrenAfflType {

    @XmlElement(name = "ChildAffl", required = true)
    protected List<ChildAffl> childAffl;
    @XmlAttribute(name = "user_defined_order")
    protected String userDefinedOrder;

    /**
     * Gets the value of the childAffl property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childAffl property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildAffl().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildrenAfflType.ChildAffl }
     *
     *
     */
    public List<ChildAffl> getChildAffl() {
        if (childAffl == null) {
            childAffl = new ArrayList<ChildAffl>();
        }
        return this.childAffl;
    }

    /**
     * Gets the value of the userDefinedOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedOrder() {
        return userDefinedOrder;
    }

    /**
     * Sets the value of the userDefinedOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedOrder(String value) {
        this.userDefinedOrder = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="child_first_name" type="{}firstNameType" minOccurs="0"/>
     *         &lt;element name="child_last_name" type="{}lastNameType"/>
     *         &lt;element name="child_middle_init_or_name" type="{}middleNameType" minOccurs="0"/>
     *         &lt;element name="child_name_prefix" type="{}namePrefixType" minOccurs="0"/>
     *         &lt;element name="child_name_suffix" type="{}nameSuffixType" minOccurs="0"/>
     *         &lt;element name="child_prof_suffix" type="{}profSuffixType" minOccurs="0"/>
     *         &lt;element name="child_ind_punctuated_name" type="{}indPunctuatedNameType" minOccurs="0"/>
     *         &lt;element name="child_pos_title" type="{}string140" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="child_firmsite_url" type="{}string100" />
     *       &lt;attribute name="child_guid" type="{}guidType" />
     *       &lt;attribute name="child_of_branch_flag" type="{}yesNoFlag" />
     *       &lt;attribute name="child_org_profile_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="child_org_wld_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="child_profession_code" type="{}professionCodeType" />
     *       &lt;attribute name="child_profile_id" type="{}profileIdType" />
     *       &lt;attribute name="child_status_code" type="{}statusCodeType" />
     *       &lt;attribute name="child_wld_id" type="{}wldIdType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "childFirstName",
        "childLastName",
        "childMiddleInitOrName",
        "childNamePrefix",
        "childNameSuffix",
        "childProfSuffix",
        "childIndPunctuatedName",
        "childPosTitle"
    })
    public static class ChildAffl {

        @XmlElement(name = "child_first_name")
        protected String childFirstName;
        @XmlElement(name = "child_last_name", required = true)
        protected String childLastName;
        @XmlElement(name = "child_middle_init_or_name")
        protected String childMiddleInitOrName;
        @XmlElement(name = "child_name_prefix")
        protected String childNamePrefix;
        @XmlElement(name = "child_name_suffix")
        protected String childNameSuffix;
        @XmlElement(name = "child_prof_suffix")
        protected String childProfSuffix;
        @XmlElement(name = "child_ind_punctuated_name")
        protected String childIndPunctuatedName;
        @XmlElement(name = "child_pos_title")
        protected String childPosTitle;
        @XmlAttribute(name = "child_firmsite_url")
        protected String childFirmsiteUrl;
        @XmlAttribute(name = "child_guid")
        protected String childGuid;
        @XmlAttribute(name = "child_of_branch_flag")
        protected String childOfBranchFlag;
        @XmlAttribute(name = "child_org_profile_id")
        protected String childOrgProfileId;
        @XmlAttribute(name = "child_org_wld_id")
        protected String childOrgWldId;
        @XmlAttribute(name = "child_profession_code")
        protected String childProfessionCode;
        @XmlAttribute(name = "child_profile_id")
        protected Integer childProfileId;
        @XmlAttribute(name = "child_status_code")
        protected StatusCodeType childStatusCode;
        @XmlAttribute(name = "child_wld_id")
        protected Integer childWldId;

        /**
         * Gets the value of the childFirstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChildFirstName() {
            return childFirstName;
        }

        /**
         * Sets the value of the childFirstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChildFirstName(String value) {
            this.childFirstName = value;
        }

        /**
         * Gets the value of the childLastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChildLastName() {
            return childLastName;
        }

        /**
         * Sets the value of the childLastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChildLastName(String value) {
            this.childLastName = value;
        }

        /**
         * Gets the value of the childMiddleInitOrName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChildMiddleInitOrName() {
            return childMiddleInitOrName;
        }

        /**
         * Sets the value of the childMiddleInitOrName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChildMiddleInitOrName(String value) {
            this.childMiddleInitOrName = value;
        }

        /**
         * Gets the value of the childNamePrefix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChildNamePrefix() {
            return childNamePrefix;
        }

        /**
         * Sets the value of the childNamePrefix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChildNamePrefix(String value) {
            this.childNamePrefix = value;
        }

        /**
         * Gets the value of the childNameSuffix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChildNameSuffix() {
            return childNameSuffix;
        }

        /**
         * Sets the value of the childNameSuffix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChildNameSuffix(String value) {
            this.childNameSuffix = value;
        }

        /**
         * Gets the value of the childProfSuffix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChildProfSuffix() {
            return childProfSuffix;
        }

        /**
         * Sets the value of the childProfSuffix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChildProfSuffix(String value) {
            this.childProfSuffix = value;
        }

        /**
         * Gets the value of the childIndPunctuatedName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChildIndPunctuatedName() {
            return childIndPunctuatedName;
        }

        /**
         * Sets the value of the childIndPunctuatedName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChildIndPunctuatedName(String value) {
            this.childIndPunctuatedName = value;
        }

        /**
         * Gets the value of the childPosTitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChildPosTitle() {
            return childPosTitle;
        }

        /**
         * Sets the value of the childPosTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChildPosTitle(String value) {
            this.childPosTitle = value;
        }

        /**
         * Gets the value of the childFirmsiteUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChildFirmsiteUrl() {
            return childFirmsiteUrl;
        }

        /**
         * Sets the value of the childFirmsiteUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChildFirmsiteUrl(String value) {
            this.childFirmsiteUrl = value;
        }

        /**
         * Gets the value of the childGuid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChildGuid() {
            return childGuid;
        }

        /**
         * Sets the value of the childGuid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChildGuid(String value) {
            this.childGuid = value;
        }

        /**
         * Gets the value of the childOfBranchFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChildOfBranchFlag() {
            return childOfBranchFlag;
        }

        /**
         * Sets the value of the childOfBranchFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChildOfBranchFlag(String value) {
            this.childOfBranchFlag = value;
        }

        /**
         * Gets the value of the childOrgProfileId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChildOrgProfileId() {
            return childOrgProfileId;
        }

        /**
         * Sets the value of the childOrgProfileId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChildOrgProfileId(String value) {
            this.childOrgProfileId = value;
        }

        /**
         * Gets the value of the childOrgWldId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChildOrgWldId() {
            return childOrgWldId;
        }

        /**
         * Sets the value of the childOrgWldId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChildOrgWldId(String value) {
            this.childOrgWldId = value;
        }

        /**
         * Gets the value of the childProfessionCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChildProfessionCode() {
            return childProfessionCode;
        }

        /**
         * Sets the value of the childProfessionCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChildProfessionCode(String value) {
            this.childProfessionCode = value;
        }

        /**
         * Gets the value of the childProfileId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getChildProfileId() {
            return childProfileId;
        }

        /**
         * Sets the value of the childProfileId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setChildProfileId(Integer value) {
            this.childProfileId = value;
        }

        /**
         * Gets the value of the childStatusCode property.
         * 
         * @return
         *     possible object is
         *     {@link StatusCodeType }
         *     
         */
        public StatusCodeType getChildStatusCode() {
            return childStatusCode;
        }

        /**
         * Sets the value of the childStatusCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link StatusCodeType }
         *     
         */
        public void setChildStatusCode(StatusCodeType value) {
            this.childStatusCode = value;
        }

        /**
         * Gets the value of the childWldId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getChildWldId() {
            return childWldId;
        }

        /**
         * Sets the value of the childWldId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setChildWldId(Integer value) {
            this.childWldId = value;
        }

    }

}
