//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for contactListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contactListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Contact" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cnt_name" type="{}string60" minOccurs="0"/>
 *                   &lt;element name="cnt_pos_title" type="{}string50" minOccurs="0"/>
 *                   &lt;element name="cnt_email_addr" type="{}emailAddrType" minOccurs="0"/>
 *                   &lt;element name="cnt_phone_num" type="{}string25" minOccurs="0"/>
 *                   &lt;element name="cnt_fax_num" type="{}string25" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contactListType", propOrder = {
    "contact"
})
public class ContactListType {

    @XmlElement(name = "Contact", required = true)
    protected List<Contact> contact;

    /**
     * Gets the value of the contact property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contact property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContact().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactListType.Contact }
     *
     *
     */
    public List<Contact> getContact() {
        if (contact == null) {
            contact = new ArrayList<Contact>();
        }
        return this.contact;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cnt_name" type="{}string60" minOccurs="0"/>
     *         &lt;element name="cnt_pos_title" type="{}string50" minOccurs="0"/>
     *         &lt;element name="cnt_email_addr" type="{}emailAddrType" minOccurs="0"/>
     *         &lt;element name="cnt_phone_num" type="{}string25" minOccurs="0"/>
     *         &lt;element name="cnt_fax_num" type="{}string25" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cntName",
        "cntPosTitle",
        "cntEmailAddr",
        "cntPhoneNum",
        "cntFaxNum"
    })
    public static class Contact {

        @XmlElement(name = "cnt_name")
        protected String cntName;
        @XmlElement(name = "cnt_pos_title")
        protected String cntPosTitle;
        @XmlElement(name = "cnt_email_addr")
        protected String cntEmailAddr;
        @XmlElement(name = "cnt_phone_num")
        protected String cntPhoneNum;
        @XmlElement(name = "cnt_fax_num")
        protected String cntFaxNum;

        /**
         * Gets the value of the cntName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCntName() {
            return cntName;
        }

        /**
         * Sets the value of the cntName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCntName(String value) {
            this.cntName = value;
        }

        /**
         * Gets the value of the cntPosTitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCntPosTitle() {
            return cntPosTitle;
        }

        /**
         * Sets the value of the cntPosTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCntPosTitle(String value) {
            this.cntPosTitle = value;
        }

        /**
         * Gets the value of the cntEmailAddr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCntEmailAddr() {
            return cntEmailAddr;
        }

        /**
         * Sets the value of the cntEmailAddr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCntEmailAddr(String value) {
            this.cntEmailAddr = value;
        }

        /**
         * Gets the value of the cntPhoneNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCntPhoneNum() {
            return cntPhoneNum;
        }

        /**
         * Sets the value of the cntPhoneNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCntPhoneNum(String value) {
            this.cntPhoneNum = value;
        }

        /**
         * Gets the value of the cntFaxNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCntFaxNum() {
            return cntFaxNum;
        }

        /**
         * Sets the value of the cntFaxNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCntFaxNum(String value) {
            this.cntFaxNum = value;
        }

    }

}
