//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for firmsitePAsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="firmsitePAsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="firmsite_pa" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="firmsite_practice_code" type="{}digit5"/>
 *                   &lt;element name="firmsite_topical_code" type="{}digit3" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="firmsite_practice_desc" type="{}string80"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "firmsitePAsType", propOrder = {
    "firmsitePa"
})
public class FirmsitePAsType {

    @XmlElement(name = "firmsite_pa", required = true)
    protected List<FirmsitePa> firmsitePa;

    /**
     * Gets the value of the firmsitePa property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the firmsitePa property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFirmsitePa().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FirmsitePAsType.FirmsitePa }
     *
     *
     */
    public List<FirmsitePa> getFirmsitePa() {
        if (firmsitePa == null) {
            firmsitePa = new ArrayList<FirmsitePa>();
        }
        return this.firmsitePa;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="firmsite_practice_code" type="{}digit5"/>
     *         &lt;element name="firmsite_topical_code" type="{}digit3" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="firmsite_practice_desc" type="{}string80"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "firmsitePracticeCode",
        "firmsiteTopicalCode",
        "firmsitePracticeDesc"
    })
    public static class FirmsitePa {

        @XmlElement(name = "firmsite_practice_code", required = true)
        protected BigInteger firmsitePracticeCode;
        @XmlElement(name = "firmsite_topical_code")
        protected List<BigInteger> firmsiteTopicalCode;
        @XmlElement(name = "firmsite_practice_desc", required = true)
        protected String firmsitePracticeDesc;

        /**
         * Gets the value of the firmsitePracticeCode property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getFirmsitePracticeCode() {
            return firmsitePracticeCode;
        }

        /**
         * Sets the value of the firmsitePracticeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setFirmsitePracticeCode(BigInteger value) {
            this.firmsitePracticeCode = value;
        }

        /**
         * Gets the value of the firmsiteTopicalCode property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the firmsiteTopicalCode property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFirmsiteTopicalCode().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BigInteger }
         * 
         * 
         */
        public List<BigInteger> getFirmsiteTopicalCode() {
            if (firmsiteTopicalCode == null) {
                firmsiteTopicalCode = new ArrayList<BigInteger>();
            }
            return this.firmsiteTopicalCode;
        }

        /**
         * Gets the value of the firmsitePracticeDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirmsitePracticeDesc() {
            return firmsitePracticeDesc;
        }

        /**
         * Sets the value of the firmsitePracticeDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirmsitePracticeDesc(String value) {
            this.firmsitePracticeDesc = value;
        }

    }

}
