//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for firmsiteUrlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="firmsiteUrlType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="firmsite_URL_addr" type="{}string100" minOccurs="0"/>
 *         &lt;element name="firmsite_URL_notes" type="{}string70" minOccurs="0"/>
 *         &lt;element name="firmsite_level" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="firmsite_pas" type="{}firmsitePAsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="default" type="{}yesNoFlag" />
 *       &lt;attribute name="has_video" type="{}yesNoFlag" />
 *       &lt;attribute name="inherited_fu" type="{}yesNoFlag" />
 *       &lt;attribute name="sub_id" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "firmsiteUrlType", propOrder = {
    "firmsiteURLAddr",
    "firmsiteURLNotes",
    "firmsiteLevel",
    "firmsitePas"
})
public class FirmsiteUrlType {

    @XmlElement(name = "firmsite_URL_addr")
    protected String firmsiteURLAddr;
    @XmlElement(name = "firmsite_URL_notes")
    protected String firmsiteURLNotes;
    @XmlElement(name = "firmsite_level")
    protected Integer firmsiteLevel;
    @XmlElement(name = "firmsite_pas")
    protected FirmsitePAsType firmsitePas;
    @XmlAttribute(name = "default")
    protected String _default;
    @XmlAttribute(name = "has_video")
    protected String hasVideo;
    @XmlAttribute(name = "inherited_fu")
    protected String inheritedFu;
    @XmlAttribute(name = "sub_id")
    protected BigInteger subId;

    /**
     * Gets the value of the firmsiteURLAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirmsiteURLAddr() {
        return firmsiteURLAddr;
    }

    /**
     * Sets the value of the firmsiteURLAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirmsiteURLAddr(String value) {
        this.firmsiteURLAddr = value;
    }

    /**
     * Gets the value of the firmsiteURLNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirmsiteURLNotes() {
        return firmsiteURLNotes;
    }

    /**
     * Sets the value of the firmsiteURLNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirmsiteURLNotes(String value) {
        this.firmsiteURLNotes = value;
    }

    /**
     * Gets the value of the firmsiteLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFirmsiteLevel() {
        return firmsiteLevel;
    }

    /**
     * Sets the value of the firmsiteLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFirmsiteLevel(Integer value) {
        this.firmsiteLevel = value;
    }

    /**
     * Gets the value of the firmsitePas property.
     * 
     * @return
     *     possible object is
     *     {@link FirmsitePAsType }
     *     
     */
    public FirmsitePAsType getFirmsitePas() {
        return firmsitePas;
    }

    /**
     * Sets the value of the firmsitePas property.
     * 
     * @param value
     *     allowed object is
     *     {@link FirmsitePAsType }
     *     
     */
    public void setFirmsitePas(FirmsitePAsType value) {
        this.firmsitePas = value;
    }

    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefault(String value) {
        this._default = value;
    }

    /**
     * Gets the value of the hasVideo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasVideo() {
        return hasVideo;
    }

    /**
     * Sets the value of the hasVideo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasVideo(String value) {
        this.hasVideo = value;
    }

    /**
     * Gets the value of the inheritedFu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInheritedFu() {
        return inheritedFu;
    }

    /**
     * Sets the value of the inheritedFu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInheritedFu(String value) {
        this.inheritedFu = value;
    }

    /**
     * Gets the value of the subId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubId() {
        return subId;
    }

    /**
     * Sets the value of the subId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubId(BigInteger value) {
        this.subId = value;
    }

}
