//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for flVideoTreeGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="flVideoTreeGroupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fl_video_tree_group_video" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="fv_tree_group_video_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fv_tree_group_video_root" type="{}yesNoFlag" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="fv_tree_group_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flVideoTreeGroupType", propOrder = {
    "flVideoTreeGroupVideo"
})
public class FlVideoTreeGroupType {

    @XmlElement(name = "fl_video_tree_group_video", required = true)
    protected List<FlVideoTreeGroupVideo> flVideoTreeGroupVideo;
    @XmlAttribute(name = "fv_tree_group_id")
    protected String fvTreeGroupId;

    /**
     * Gets the value of the flVideoTreeGroupVideo property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flVideoTreeGroupVideo property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlVideoTreeGroupVideo().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlVideoTreeGroupType.FlVideoTreeGroupVideo }
     *
     *
     */
    public List<FlVideoTreeGroupVideo> getFlVideoTreeGroupVideo() {
        if (flVideoTreeGroupVideo == null) {
            flVideoTreeGroupVideo = new ArrayList<FlVideoTreeGroupVideo>();
        }
        return this.flVideoTreeGroupVideo;
    }

    /**
     * Gets the value of the fvTreeGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFvTreeGroupId() {
        return fvTreeGroupId;
    }

    /**
     * Sets the value of the fvTreeGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFvTreeGroupId(String value) {
        this.fvTreeGroupId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="fv_tree_group_video_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fv_tree_group_video_root" type="{}yesNoFlag" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class FlVideoTreeGroupVideo {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "fv_tree_group_video_id")
        protected String fvTreeGroupVideoId;
        @XmlAttribute(name = "fv_tree_group_video_root")
        protected String fvTreeGroupVideoRoot;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the fvTreeGroupVideoId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFvTreeGroupVideoId() {
            return fvTreeGroupVideoId;
        }

        /**
         * Sets the value of the fvTreeGroupVideoId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFvTreeGroupVideoId(String value) {
            this.fvTreeGroupVideoId = value;
        }

        /**
         * Gets the value of the fvTreeGroupVideoRoot property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFvTreeGroupVideoRoot() {
            return fvTreeGroupVideoRoot;
        }

        /**
         * Sets the value of the fvTreeGroupVideoRoot property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFvTreeGroupVideoRoot(String value) {
            this.fvTreeGroupVideoRoot = value;
        }

    }

}
