//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for individualType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="individualType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IndName" type="{}indNameType"/>
 *         &lt;element name="YearJoinedFirm" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>digitYearType">
 *                 &lt;attribute name="year_type" type="{}yearType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Born" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="date_of_birth" type="{}allDigitsDateType" minOccurs="0"/>
 *                   &lt;element name="city_of_birth" type="{}string40" minOccurs="0"/>
 *                   &lt;element name="state_of_birth" type="{}string25" minOccurs="0"/>
 *                   &lt;element name="country_of_birth" type="{}string30" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "individualType", propOrder = {
    "indName",
    "yearJoinedFirm",
    "born"
})
public class IndividualType {

    @XmlElement(name = "IndName", required = true)
    protected IndNameType indName;
    @XmlElement(name = "YearJoinedFirm")
    protected IndividualType.YearJoinedFirm yearJoinedFirm;
    @XmlElement(name = "Born")
    protected IndividualType.Born born;

    /**
     * Gets the value of the indName property.
     *
     * @return
     *     possible object is
     *     {@link IndNameType }
     *
     */
    public IndNameType getIndName() {
        return indName;
    }

    /**
     * Sets the value of the indName property.
     *
     * @param value
     *     allowed object is
     *     {@link IndNameType }
     *
     */
    public void setIndName(IndNameType value) {
        this.indName = value;
    }

    /**
     * Gets the value of the yearJoinedFirm property.
     *
     * @return
     *     possible object is
     *     {@link IndividualType.YearJoinedFirm }
     *
     */
    public IndividualType.YearJoinedFirm getYearJoinedFirm() {
        return yearJoinedFirm;
    }

    /**
     * Sets the value of the yearJoinedFirm property.
     *
     * @param value
     *     allowed object is
     *     {@link IndividualType.YearJoinedFirm }
     *
     */
    public void setYearJoinedFirm(IndividualType.YearJoinedFirm value) {
        this.yearJoinedFirm = value;
    }

    /**
     * Gets the value of the born property.
     *
     * @return
     *     possible object is
     *     {@link IndividualType.Born }
     *
     */
    public IndividualType.Born getBorn() {
        return born;
    }

    /**
     * Sets the value of the born property.
     *
     * @param value
     *     allowed object is
     *     {@link IndividualType.Born }
     *
     */
    public void setBorn(IndividualType.Born value) {
        this.born = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="date_of_birth" type="{}allDigitsDateType" minOccurs="0"/>
     *         &lt;element name="city_of_birth" type="{}string40" minOccurs="0"/>
     *         &lt;element name="state_of_birth" type="{}string25" minOccurs="0"/>
     *         &lt;element name="country_of_birth" type="{}string30" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dateOfBirth",
        "cityOfBirth",
        "stateOfBirth",
        "countryOfBirth"
    })
    public static class Born {

        @XmlElement(name = "date_of_birth")
        protected String dateOfBirth;
        @XmlElement(name = "city_of_birth")
        protected String cityOfBirth;
        @XmlElement(name = "state_of_birth")
        protected String stateOfBirth;
        @XmlElement(name = "country_of_birth")
        protected String countryOfBirth;

        /**
         * Gets the value of the dateOfBirth property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDateOfBirth() {
            return dateOfBirth;
        }

        /**
         * Sets the value of the dateOfBirth property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDateOfBirth(String value) {
            this.dateOfBirth = value;
        }

        /**
         * Gets the value of the cityOfBirth property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCityOfBirth() {
            return cityOfBirth;
        }

        /**
         * Sets the value of the cityOfBirth property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCityOfBirth(String value) {
            this.cityOfBirth = value;
        }

        /**
         * Gets the value of the stateOfBirth property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStateOfBirth() {
            return stateOfBirth;
        }

        /**
         * Sets the value of the stateOfBirth property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStateOfBirth(String value) {
            this.stateOfBirth = value;
        }

        /**
         * Gets the value of the countryOfBirth property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryOfBirth() {
            return countryOfBirth;
        }

        /**
         * Sets the value of the countryOfBirth property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryOfBirth(String value) {
            this.countryOfBirth = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>digitYearType">
     *       &lt;attribute name="year_type" type="{}yearType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class YearJoinedFirm {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "year_type")
        protected YearType yearType;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the yearType property.
         * 
         * @return
         *     possible object is
         *     {@link YearType }
         *     
         */
        public YearType getYearType() {
            return yearType;
        }

        /**
         * Sets the value of the yearType property.
         * 
         * @param value
         *     allowed object is
         *     {@link YearType }
         *     
         */
        public void setYearType(YearType value) {
            this.yearType = value;
        }

    }

}
