//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for leMajorsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="leMajorsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LE_Major" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LE_Major_Minor_desc" type="{}string70"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="LE_major_flag">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="Major"/>
 *                       &lt;enumeration value="Minor"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "leMajorsType", propOrder = {
    "leMajor"
})
public class LeMajorsType {

    @XmlElement(name = "LE_Major", required = true)
    protected List<LEMajor> leMajor;

    /**
     * Gets the value of the leMajor property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the leMajor property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLEMajor().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LeMajorsType.LEMajor }
     *
     *
     */
    public List<LEMajor> getLEMajor() {
        if (leMajor == null) {
            leMajor = new ArrayList<LEMajor>();
        }
        return this.leMajor;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LE_Major_Minor_desc" type="{}string70"/>
     *       &lt;/sequence>
     *       &lt;attribute name="LE_major_flag">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="Major"/>
     *             &lt;enumeration value="Minor"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "leMajorMinorDesc"
    })
    public static class LEMajor {

        @XmlElement(name = "LE_Major_Minor_desc", required = true)
        protected String leMajorMinorDesc;
        @XmlAttribute(name = "LE_major_flag")
        protected String leMajorFlag;

        /**
         * Gets the value of the leMajorMinorDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLEMajorMinorDesc() {
            return leMajorMinorDesc;
        }

        /**
         * Sets the value of the leMajorMinorDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLEMajorMinorDesc(String value) {
            this.leMajorMinorDesc = value;
        }

        /**
         * Gets the value of the leMajorFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLEMajorFlag() {
            return leMajorFlag;
        }

        /**
         * Sets the value of the leMajorFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLEMajorFlag(String value) {
            this.leMajorFlag = value;
        }

    }

}
