//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for leType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="leType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LE_school_loc_seq_num" type="{}digit7"/>
 *         &lt;element name="LE_school_name" type="{}string140"/>
 *         &lt;element name="LE_distinction_code" type="{}leDistinctionCodeType" minOccurs="0"/>
 *         &lt;element name="LE_grad_date" type="{}allDigitsDateType" minOccurs="0"/>
 *         &lt;element name="LE_degree_desc" type="{}string140" minOccurs="0"/>
 *         &lt;element name="LE_city" type="{}string40" minOccurs="0"/>
 *         &lt;element name="LE_state" type="{}string25" minOccurs="0"/>
 *         &lt;element name="LE_state_abbr" type="{}string3" minOccurs="0"/>
 *         &lt;element name="LE_country" type="{}string30" minOccurs="0"/>
 *         &lt;element name="LE_advocacy_flag" type="{}yesNoFlag" minOccurs="0"/>
 *         &lt;element name="LE_class_rank_text" type="{}string15" minOccurs="0"/>
 *         &lt;element name="LE_clinical_flag" type="{}yesNoFlag" minOccurs="0"/>
 *         &lt;element name="LE_gpa" type="{}string20" minOccurs="0"/>
 *         &lt;element name="LE_law_journal_flag" type="{}yesNoFlag" minOccurs="0"/>
 *         &lt;element name="LE_law_review_flag" type="{}yesNoFlag" minOccurs="0"/>
 *         &lt;element name="LE_max_gpa" type="{}string20" minOccurs="0"/>
 *         &lt;element name="LE_moot_court_flag" type="{}yesNoFlag" minOccurs="0"/>
 *         &lt;element name="LE_other_text" type="{}string70" minOccurs="0"/>
 *         &lt;element name="LE_research_flag" type="{}yesNoFlag" minOccurs="0"/>
 *         &lt;element name="LE_student_govn_flag" type="{}yesNoFlag" minOccurs="0"/>
 *         &lt;element name="LE_student_org_flag" type="{}yesNoFlag" minOccurs="0"/>
 *         &lt;element name="LE_tutor_flag" type="{}yesNoFlag" minOccurs="0"/>
 *         &lt;element name="LE_SchoolHonors" type="{}leSchoolHonorsType" minOccurs="0"/>
 *         &lt;element name="LE_Majors" type="{}leMajorsType" minOccurs="0"/>
 *         &lt;element name="LawPubs" type="{}lawPubsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="LE_edu_seq_num" type="{}digit9" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "leType", propOrder = {
    "leSchoolLocSeqNum",
    "leSchoolName",
    "leDistinctionCode",
    "leGradDate",
    "leDegreeDesc",
    "leCity",
    "leState",
    "leStateAbbr",
    "leCountry",
    "leAdvocacyFlag",
    "leClassRankText",
    "leClinicalFlag",
    "leGpa",
    "leLawJournalFlag",
    "leLawReviewFlag",
    "leMaxGpa",
    "leMootCourtFlag",
    "leOtherText",
    "leResearchFlag",
    "leStudentGovnFlag",
    "leStudentOrgFlag",
    "leTutorFlag",
    "leSchoolHonors",
    "leMajors",
    "lawPubs"
})
public class LeType {

    @XmlElement(name = "LE_school_loc_seq_num", required = true)
    protected String leSchoolLocSeqNum;
    @XmlElement(name = "LE_school_name", required = true)
    protected String leSchoolName;
    @XmlElement(name = "LE_distinction_code")
    protected String leDistinctionCode;
    @XmlElement(name = "LE_grad_date")
    protected String leGradDate;
    @XmlElement(name = "LE_degree_desc")
    protected String leDegreeDesc;
    @XmlElement(name = "LE_city")
    protected String leCity;
    @XmlElement(name = "LE_state")
    protected String leState;
    @XmlElement(name = "LE_state_abbr")
    protected String leStateAbbr;
    @XmlElement(name = "LE_country")
    protected String leCountry;
    @XmlElement(name = "LE_advocacy_flag")
    protected String leAdvocacyFlag;
    @XmlElement(name = "LE_class_rank_text")
    protected String leClassRankText;
    @XmlElement(name = "LE_clinical_flag")
    protected String leClinicalFlag;
    @XmlElement(name = "LE_gpa")
    protected String leGpa;
    @XmlElement(name = "LE_law_journal_flag")
    protected String leLawJournalFlag;
    @XmlElement(name = "LE_law_review_flag")
    protected String leLawReviewFlag;
    @XmlElement(name = "LE_max_gpa")
    protected String leMaxGpa;
    @XmlElement(name = "LE_moot_court_flag")
    protected String leMootCourtFlag;
    @XmlElement(name = "LE_other_text")
    protected String leOtherText;
    @XmlElement(name = "LE_research_flag")
    protected String leResearchFlag;
    @XmlElement(name = "LE_student_govn_flag")
    protected String leStudentGovnFlag;
    @XmlElement(name = "LE_student_org_flag")
    protected String leStudentOrgFlag;
    @XmlElement(name = "LE_tutor_flag")
    protected String leTutorFlag;
    @XmlElement(name = "LE_SchoolHonors")
    protected LeSchoolHonorsType leSchoolHonors;
    @XmlElement(name = "LE_Majors")
    protected LeMajorsType leMajors;
    @XmlElement(name = "LawPubs")
    protected LawPubsType lawPubs;
    @XmlAttribute(name = "LE_edu_seq_num")
    protected BigInteger leEduSeqNum;

    /**
     * Gets the value of the leSchoolLocSeqNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLESchoolLocSeqNum() {
        return leSchoolLocSeqNum;
    }

    /**
     * Sets the value of the leSchoolLocSeqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLESchoolLocSeqNum(String value) {
        this.leSchoolLocSeqNum = value;
    }

    /**
     * Gets the value of the leSchoolName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLESchoolName() {
        return leSchoolName;
    }

    /**
     * Sets the value of the leSchoolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLESchoolName(String value) {
        this.leSchoolName = value;
    }

    /**
     * Gets the value of the leDistinctionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEDistinctionCode() {
        return leDistinctionCode;
    }

    /**
     * Sets the value of the leDistinctionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEDistinctionCode(String value) {
        this.leDistinctionCode = value;
    }

    /**
     * Gets the value of the leGradDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEGradDate() {
        return leGradDate;
    }

    /**
     * Sets the value of the leGradDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEGradDate(String value) {
        this.leGradDate = value;
    }

    /**
     * Gets the value of the leDegreeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEDegreeDesc() {
        return leDegreeDesc;
    }

    /**
     * Sets the value of the leDegreeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEDegreeDesc(String value) {
        this.leDegreeDesc = value;
    }

    /**
     * Gets the value of the leCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLECity() {
        return leCity;
    }

    /**
     * Sets the value of the leCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLECity(String value) {
        this.leCity = value;
    }

    /**
     * Gets the value of the leState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEState() {
        return leState;
    }

    /**
     * Sets the value of the leState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEState(String value) {
        this.leState = value;
    }

    /**
     * Gets the value of the leStateAbbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEStateAbbr() {
        return leStateAbbr;
    }

    /**
     * Sets the value of the leStateAbbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEStateAbbr(String value) {
        this.leStateAbbr = value;
    }

    /**
     * Gets the value of the leCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLECountry() {
        return leCountry;
    }

    /**
     * Sets the value of the leCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLECountry(String value) {
        this.leCountry = value;
    }

    /**
     * Gets the value of the leAdvocacyFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEAdvocacyFlag() {
        return leAdvocacyFlag;
    }

    /**
     * Sets the value of the leAdvocacyFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEAdvocacyFlag(String value) {
        this.leAdvocacyFlag = value;
    }

    /**
     * Gets the value of the leClassRankText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEClassRankText() {
        return leClassRankText;
    }

    /**
     * Sets the value of the leClassRankText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEClassRankText(String value) {
        this.leClassRankText = value;
    }

    /**
     * Gets the value of the leClinicalFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEClinicalFlag() {
        return leClinicalFlag;
    }

    /**
     * Sets the value of the leClinicalFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEClinicalFlag(String value) {
        this.leClinicalFlag = value;
    }

    /**
     * Gets the value of the leGpa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEGpa() {
        return leGpa;
    }

    /**
     * Sets the value of the leGpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEGpa(String value) {
        this.leGpa = value;
    }

    /**
     * Gets the value of the leLawJournalFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLELawJournalFlag() {
        return leLawJournalFlag;
    }

    /**
     * Sets the value of the leLawJournalFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLELawJournalFlag(String value) {
        this.leLawJournalFlag = value;
    }

    /**
     * Gets the value of the leLawReviewFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLELawReviewFlag() {
        return leLawReviewFlag;
    }

    /**
     * Sets the value of the leLawReviewFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLELawReviewFlag(String value) {
        this.leLawReviewFlag = value;
    }

    /**
     * Gets the value of the leMaxGpa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEMaxGpa() {
        return leMaxGpa;
    }

    /**
     * Sets the value of the leMaxGpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEMaxGpa(String value) {
        this.leMaxGpa = value;
    }

    /**
     * Gets the value of the leMootCourtFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEMootCourtFlag() {
        return leMootCourtFlag;
    }

    /**
     * Sets the value of the leMootCourtFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEMootCourtFlag(String value) {
        this.leMootCourtFlag = value;
    }

    /**
     * Gets the value of the leOtherText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEOtherText() {
        return leOtherText;
    }

    /**
     * Sets the value of the leOtherText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEOtherText(String value) {
        this.leOtherText = value;
    }

    /**
     * Gets the value of the leResearchFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEResearchFlag() {
        return leResearchFlag;
    }

    /**
     * Sets the value of the leResearchFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEResearchFlag(String value) {
        this.leResearchFlag = value;
    }

    /**
     * Gets the value of the leStudentGovnFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEStudentGovnFlag() {
        return leStudentGovnFlag;
    }

    /**
     * Sets the value of the leStudentGovnFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEStudentGovnFlag(String value) {
        this.leStudentGovnFlag = value;
    }

    /**
     * Gets the value of the leStudentOrgFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEStudentOrgFlag() {
        return leStudentOrgFlag;
    }

    /**
     * Sets the value of the leStudentOrgFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEStudentOrgFlag(String value) {
        this.leStudentOrgFlag = value;
    }

    /**
     * Gets the value of the leTutorFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLETutorFlag() {
        return leTutorFlag;
    }

    /**
     * Sets the value of the leTutorFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLETutorFlag(String value) {
        this.leTutorFlag = value;
    }

    /**
     * Gets the value of the leSchoolHonors property.
     * 
     * @return
     *     possible object is
     *     {@link LeSchoolHonorsType }
     *     
     */
    public LeSchoolHonorsType getLESchoolHonors() {
        return leSchoolHonors;
    }

    /**
     * Sets the value of the leSchoolHonors property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeSchoolHonorsType }
     *     
     */
    public void setLESchoolHonors(LeSchoolHonorsType value) {
        this.leSchoolHonors = value;
    }

    /**
     * Gets the value of the leMajors property.
     * 
     * @return
     *     possible object is
     *     {@link LeMajorsType }
     *     
     */
    public LeMajorsType getLEMajors() {
        return leMajors;
    }

    /**
     * Sets the value of the leMajors property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeMajorsType }
     *     
     */
    public void setLEMajors(LeMajorsType value) {
        this.leMajors = value;
    }

    /**
     * Gets the value of the lawPubs property.
     * 
     * @return
     *     possible object is
     *     {@link LawPubsType }
     *     
     */
    public LawPubsType getLawPubs() {
        return lawPubs;
    }

    /**
     * Sets the value of the lawPubs property.
     * 
     * @param value
     *     allowed object is
     *     {@link LawPubsType }
     *     
     */
    public void setLawPubs(LawPubsType value) {
        this.lawPubs = value;
    }

    /**
     * Gets the value of the leEduSeqNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLEEduSeqNum() {
        return leEduSeqNum;
    }

    /**
     * Sets the value of the leEduSeqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLEEduSeqNum(BigInteger value) {
        this.leEduSeqNum = value;
    }

}
