//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lsCountryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lsCountryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LS_country_name" type="{}string30"/>
 *         &lt;element name="LS_country_code" type="{}countryCodeType"/>
 *         &lt;element name="LS_ovd_country_name" type="{}string30" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lsCountryType", propOrder = {
    "lsCountryName",
    "lsCountryCode",
    "lsOvdCountryName"
})
public class LsCountryType {

    @XmlElement(name = "LS_country_name", required = true)
    protected String lsCountryName;
    @XmlElement(name = "LS_country_code")
    protected int lsCountryCode;
    @XmlElement(name = "LS_ovd_country_name")
    protected String lsOvdCountryName;

    /**
     * Gets the value of the lsCountryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLSCountryName() {
        return lsCountryName;
    }

    /**
     * Sets the value of the lsCountryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLSCountryName(String value) {
        this.lsCountryName = value;
    }

    /**
     * Gets the value of the lsCountryCode property.
     * 
     */
    public int getLSCountryCode() {
        return lsCountryCode;
    }

    /**
     * Sets the value of the lsCountryCode property.
     * 
     */
    public void setLSCountryCode(int value) {
        this.lsCountryCode = value;
    }

    /**
     * Gets the value of the lsOvdCountryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLSOvdCountryName() {
        return lsOvdCountryName;
    }

    /**
     * Sets the value of the lsOvdCountryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLSOvdCountryName(String value) {
        this.lsOvdCountryName = value;
    }

}
