//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for memberAssocPcsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="memberAssocPcsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Member_Assoc_PC" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="mem_assoc_pc_desc" type="{}string100"/>
 *                   &lt;element name="mem_assoc_pc_pct" type="{}percentageType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="mem_assoc_pc_id" type="{}digit8" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "memberAssocPcsType", propOrder = {
    "memberAssocPC"
})
public class MemberAssocPcsType {

    @XmlElement(name = "Member_Assoc_PC", required = true)
    protected List<MemberAssocPC> memberAssocPC;

    /**
     * Gets the value of the memberAssocPC property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the memberAssocPC property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMemberAssocPC().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MemberAssocPcsType.MemberAssocPC }
     *
     *
     */
    public List<MemberAssocPC> getMemberAssocPC() {
        if (memberAssocPC == null) {
            memberAssocPC = new ArrayList<MemberAssocPC>();
        }
        return this.memberAssocPC;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="mem_assoc_pc_desc" type="{}string100"/>
     *         &lt;element name="mem_assoc_pc_pct" type="{}percentageType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="mem_assoc_pc_id" type="{}digit8" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "memAssocPcDesc",
        "memAssocPcPct"
    })
    public static class MemberAssocPC {

        @XmlElement(name = "mem_assoc_pc_desc", required = true)
        protected String memAssocPcDesc;
        @XmlElement(name = "mem_assoc_pc_pct")
        protected Integer memAssocPcPct;
        @XmlAttribute(name = "mem_assoc_pc_id")
        protected BigInteger memAssocPcId;

        /**
         * Gets the value of the memAssocPcDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMemAssocPcDesc() {
            return memAssocPcDesc;
        }

        /**
         * Sets the value of the memAssocPcDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMemAssocPcDesc(String value) {
            this.memAssocPcDesc = value;
        }

        /**
         * Gets the value of the memAssocPcPct property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMemAssocPcPct() {
            return memAssocPcPct;
        }

        /**
         * Sets the value of the memAssocPcPct property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMemAssocPcPct(Integer value) {
            this.memAssocPcPct = value;
        }

        /**
         * Gets the value of the memAssocPcId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMemAssocPcId() {
            return memAssocPcId;
        }

        /**
         * Sets the value of the memAssocPcId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMemAssocPcId(BigInteger value) {
            this.memAssocPcId = value;
        }

    }

}
