//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for memOfAssocsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="memOfAssocsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mem_assoc" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Member_Assoc_PCs" type="{}memberAssocPcsType" minOccurs="0"/>
 *                   &lt;element name="mem_assoc_name" type="{}orgNameType"/>
 *                   &lt;element name="mem_creation_date" type="{}timestampType"/>
 *                 &lt;/all>
 *                 &lt;attribute name="mem_assoc_guid" type="{}guidType" />
 *                 &lt;attribute name="mem_assoc_profile_id" type="{}profileIdType" />
 *                 &lt;attribute name="mem_assoc_wld_id" type="{}wldIdType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "memOfAssocsType", propOrder = {
    "memAssoc"
})
public class MemOfAssocsType {

    @XmlElement(name = "mem_assoc", required = true)
    protected List<MemAssoc> memAssoc;

    /**
     * Gets the value of the memAssoc property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the memAssoc property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMemAssoc().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MemOfAssocsType.MemAssoc }
     *
     *
     */
    public List<MemAssoc> getMemAssoc() {
        if (memAssoc == null) {
            memAssoc = new ArrayList<MemAssoc>();
        }
        return this.memAssoc;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="Member_Assoc_PCs" type="{}memberAssocPcsType" minOccurs="0"/>
     *         &lt;element name="mem_assoc_name" type="{}orgNameType"/>
     *         &lt;element name="mem_creation_date" type="{}timestampType"/>
     *       &lt;/all>
     *       &lt;attribute name="mem_assoc_guid" type="{}guidType" />
     *       &lt;attribute name="mem_assoc_profile_id" type="{}profileIdType" />
     *       &lt;attribute name="mem_assoc_wld_id" type="{}wldIdType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class MemAssoc {

        @XmlElement(name = "Member_Assoc_PCs")
        protected MemberAssocPcsType memberAssocPCs;
        @XmlElement(name = "mem_assoc_name", required = true)
        protected String memAssocName;
        @XmlElement(name = "mem_creation_date", required = true)
        protected String memCreationDate;
        @XmlAttribute(name = "mem_assoc_guid")
        protected String memAssocGuid;
        @XmlAttribute(name = "mem_assoc_profile_id")
        protected Integer memAssocProfileId;
        @XmlAttribute(name = "mem_assoc_wld_id")
        protected Integer memAssocWldId;

        /**
         * Gets the value of the memberAssocPCs property.
         * 
         * @return
         *     possible object is
         *     {@link MemberAssocPcsType }
         *     
         */
        public MemberAssocPcsType getMemberAssocPCs() {
            return memberAssocPCs;
        }

        /**
         * Sets the value of the memberAssocPCs property.
         * 
         * @param value
         *     allowed object is
         *     {@link MemberAssocPcsType }
         *     
         */
        public void setMemberAssocPCs(MemberAssocPcsType value) {
            this.memberAssocPCs = value;
        }

        /**
         * Gets the value of the memAssocName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMemAssocName() {
            return memAssocName;
        }

        /**
         * Sets the value of the memAssocName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMemAssocName(String value) {
            this.memAssocName = value;
        }

        /**
         * Gets the value of the memCreationDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMemCreationDate() {
            return memCreationDate;
        }

        /**
         * Sets the value of the memCreationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMemCreationDate(String value) {
            this.memCreationDate = value;
        }

        /**
         * Gets the value of the memAssocGuid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMemAssocGuid() {
            return memAssocGuid;
        }

        /**
         * Sets the value of the memAssocGuid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMemAssocGuid(String value) {
            this.memAssocGuid = value;
        }

        /**
         * Gets the value of the memAssocProfileId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMemAssocProfileId() {
            return memAssocProfileId;
        }

        /**
         * Sets the value of the memAssocProfileId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMemAssocProfileId(Integer value) {
            this.memAssocProfileId = value;
        }

        /**
         * Gets the value of the memAssocWldId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMemAssocWldId() {
            return memAssocWldId;
        }

        /**
         * Sets the value of the memAssocWldId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMemAssocWldId(Integer value) {
            this.memAssocWldId = value;
        }

    }

}
