//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for mergerAcqsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mergerAcqsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MergerAcq" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="merger_name" type="{}string141"/>
 *                   &lt;element name="merger_date" type="{}allDigitsDateType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mergerAcqsType", propOrder = {
    "mergerAcq"
})
public class MergerAcqsType {

    @XmlElement(name = "MergerAcq", required = true)
    protected List<MergerAcq> mergerAcq;

    /**
     * Gets the value of the mergerAcq property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mergerAcq property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMergerAcq().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MergerAcqsType.MergerAcq }
     *
     *
     */
    public List<MergerAcq> getMergerAcq() {
        if (mergerAcq == null) {
            mergerAcq = new ArrayList<MergerAcq>();
        }
        return this.mergerAcq;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="merger_name" type="{}string141"/>
     *         &lt;element name="merger_date" type="{}allDigitsDateType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mergerName",
        "mergerDate"
    })
    public static class MergerAcq {

        @XmlElement(name = "merger_name", required = true)
        protected String mergerName;
        @XmlElement(name = "merger_date")
        protected String mergerDate;

        /**
         * Gets the value of the mergerName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMergerName() {
            return mergerName;
        }

        /**
         * Sets the value of the mergerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMergerName(String value) {
            this.mergerName = value;
        }

        /**
         * Gets the value of the mergerDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMergerDate() {
            return mergerDate;
        }

        /**
         * Sets the value of the mergerDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMergerDate(String value) {
            this.mergerDate = value;
        }

    }

}
