//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for nleMajorsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nleMajorsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NLE_Major" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NLE_Major_Minor_desc" type="{}string70"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="NLE_major_flag">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="Major"/>
 *                       &lt;enumeration value="Minor"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nleMajorsType", propOrder = {
    "nleMajor"
})
public class NleMajorsType {

    @XmlElement(name = "NLE_Major", required = true)
    protected List<NLEMajor> nleMajor;

    /**
     * Gets the value of the nleMajor property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nleMajor property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNLEMajor().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NleMajorsType.NLEMajor }
     *
     *
     */
    public List<NLEMajor> getNLEMajor() {
        if (nleMajor == null) {
            nleMajor = new ArrayList<NLEMajor>();
        }
        return this.nleMajor;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NLE_Major_Minor_desc" type="{}string70"/>
     *       &lt;/sequence>
     *       &lt;attribute name="NLE_major_flag">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="Major"/>
     *             &lt;enumeration value="Minor"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nleMajorMinorDesc"
    })
    public static class NLEMajor {

        @XmlElement(name = "NLE_Major_Minor_desc", required = true)
        protected String nleMajorMinorDesc;
        @XmlAttribute(name = "NLE_major_flag")
        protected String nleMajorFlag;

        /**
         * Gets the value of the nleMajorMinorDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNLEMajorMinorDesc() {
            return nleMajorMinorDesc;
        }

        /**
         * Sets the value of the nleMajorMinorDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNLEMajorMinorDesc(String value) {
            this.nleMajorMinorDesc = value;
        }

        /**
         * Gets the value of the nleMajorFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNLEMajorFlag() {
            return nleMajorFlag;
        }

        /**
         * Sets the value of the nleMajorFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNLEMajorFlag(String value) {
            this.nleMajorFlag = value;
        }

    }

}
