//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.11 at 03:41:56 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fl.wld.xmlbinding.jaxb.profile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PasTypePAPAPracPct_QNAME = new QName("", "PA_prac_pct");
    private final static QName _PasTypePAPATopicalCode_QNAME = new QName("", "PA_topical_code");
    private final static QName _PasTypePAPADesc_QNAME = new QName("", "PA_desc");
    private final static QName _PasTypePAPAPracticeCode_QNAME = new QName("", "PA_practice_code");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fl.wld.xmlbinding.jaxb.profile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Profile.PaymentTypes }
     * 
     */
    public Profile.PaymentTypes createProfilePaymentTypes() {
        return new Profile.PaymentTypes();
    }

    /**
     * Create an instance of {@link OoCountryType }
     * 
     */
    public OoCountryType createOoCountryType() {
        return new OoCountryType();
    }

    /**
     * Create an instance of {@link ProfilePropertiesType.ObfuscateEmailFlag }
     * 
     */
    public ProfilePropertiesType.ObfuscateEmailFlag createProfilePropertiesTypeObfuscateEmailFlag() {
        return new ProfilePropertiesType.ObfuscateEmailFlag();
    }

    /**
     * Create an instance of {@link EmailType }
     * 
     */
    public EmailType createEmailType() {
        return new EmailType();
    }

    /**
     * Create an instance of {@link PrevVanityUrlsType.PrevVanityURL }
     * 
     */
    public PrevVanityUrlsType.PrevVanityURL createPrevVanityUrlsTypePrevVanityURL() {
        return new PrevVanityUrlsType.PrevVanityURL();
    }

    /**
     * Create an instance of {@link LsStateType }
     * 
     */
    public LsStateType createLsStateType() {
        return new LsStateType();
    }

    /**
     * Create an instance of {@link FirmsitePAsType }
     * 
     */
    public FirmsitePAsType createFirmsitePAsType() {
        return new FirmsitePAsType();
    }

    /**
     * Create an instance of {@link LawInfoContactFormType.LiCallTimes.LiCallTime }
     * 
     */
    public LawInfoContactFormType.LiCallTimes.LiCallTime createLawInfoContactFormTypeLiCallTimesLiCallTime() {
        return new LawInfoContactFormType.LiCallTimes.LiCallTime();
    }

    /**
     * Create an instance of {@link AssocMemberIndType }
     * 
     */
    public AssocMemberIndType createAssocMemberIndType() {
        return new AssocMemberIndType();
    }

    /**
     * Create an instance of {@link Profile.PaymentPlansAccepted }
     * 
     */
    public Profile.PaymentPlansAccepted createProfilePaymentPlansAccepted() {
        return new Profile.PaymentPlansAccepted();
    }

    /**
     * Create an instance of {@link MemberAssocPcsType.MemberAssocPC }
     * 
     */
    public MemberAssocPcsType.MemberAssocPC createMemberAssocPcsTypeMemberAssocPC() {
        return new MemberAssocPcsType.MemberAssocPC();
    }

    /**
     * Create an instance of {@link ClassesSeminarsType }
     * 
     */
    public ClassesSeminarsType createClassesSeminarsType() {
        return new ClassesSeminarsType();
    }

    /**
     * Create an instance of {@link SpecialProfileCodeType }
     * 
     */
    public SpecialProfileCodeType createSpecialProfileCodeType() {
        return new SpecialProfileCodeType();
    }

    /**
     * Create an instance of {@link StateType }
     * 
     */
    public StateType createStateType() {
        return new StateType();
    }

    /**
     * Create an instance of {@link LawInfoContactFormType.LiTimezone }
     * 
     */
    public LawInfoContactFormType.LiTimezone createLawInfoContactFormTypeLiTimezone() {
        return new LawInfoContactFormType.LiTimezone();
    }

    /**
     * Create an instance of {@link WebsiteAffiliateMatchesType.WebsiteAffiliateMatch }
     * 
     */
    public WebsiteAffiliateMatchesType.WebsiteAffiliateMatch createWebsiteAffiliateMatchesTypeWebsiteAffiliateMatch() {
        return new WebsiteAffiliateMatchesType.WebsiteAffiliateMatch();
    }

    /**
     * Create an instance of {@link PwPAsType }
     * 
     */
    public PwPAsType createPwPAsType() {
        return new PwPAsType();
    }

    /**
     * Create an instance of {@link ContactListType.Contact }
     * 
     */
    public ContactListType.Contact createContactListTypeContact() {
        return new ContactListType.Contact();
    }

    /**
     * Create an instance of {@link ProfilePropertiesType }
     * 
     */
    public ProfilePropertiesType createProfilePropertiesType() {
        return new ProfilePropertiesType();
    }

    /**
     * Create an instance of {@link HonorsType }
     * 
     */
    public HonorsType createHonorsType() {
        return new HonorsType();
    }

    /**
     * Create an instance of {@link BarAdmissionType }
     * 
     */
    public BarAdmissionType createBarAdmissionType() {
        return new BarAdmissionType();
    }

    /**
     * Create an instance of {@link ClassesSeminarsType.ClassSeminar }
     * 
     */
    public ClassesSeminarsType.ClassSeminar createClassesSeminarsTypeClassSeminar() {
        return new ClassesSeminarsType.ClassSeminar();
    }

    /**
     * Create an instance of {@link Profile.NarrativeText }
     * 
     */
    public Profile.NarrativeText createProfileNarrativeText() {
        return new Profile.NarrativeText();
    }

    /**
     * Create an instance of {@link NleType }
     * 
     */
    public NleType createNleType() {
        return new NleType();
    }

    /**
     * Create an instance of {@link PgpInternetUrlType }
     * 
     */
    public PgpInternetUrlType createPgpInternetUrlType() {
        return new PgpInternetUrlType();
    }

    /**
     * Create an instance of {@link PhoneType }
     * 
     */
    public PhoneType createPhoneType() {
        return new PhoneType();
    }

    /**
     * Create an instance of {@link PracticeGroupsType.PracticeGroup }
     * 
     */
    public PracticeGroupsType.PracticeGroup createPracticeGroupsTypePracticeGroup() {
        return new PracticeGroupsType.PracticeGroup();
    }

    /**
     * Create an instance of {@link RegionsServedType }
     * 
     */
    public RegionsServedType createRegionsServedType() {
        return new RegionsServedType();
    }

    /**
     * Create an instance of {@link PgpFirmsiteUrlsType }
     * 
     */
    public PgpFirmsiteUrlsType createPgpFirmsiteUrlsType() {
        return new PgpFirmsiteUrlsType();
    }

    /**
     * Create an instance of {@link PrevNamesType }
     * 
     */
    public PrevNamesType createPrevNamesType() {
        return new PrevNamesType();
    }

    /**
     * Create an instance of {@link FirmsiteUrlsType }
     * 
     */
    public FirmsiteUrlsType createFirmsiteUrlsType() {
        return new FirmsiteUrlsType();
    }

    /**
     * Create an instance of {@link LawInfoContactFormType.LiType }
     * 
     */
    public LawInfoContactFormType.LiType createLawInfoContactFormTypeLiType() {
        return new LawInfoContactFormType.LiType();
    }

    /**
     * Create an instance of {@link AncillaryBizsType }
     * 
     */
    public AncillaryBizsType createAncillaryBizsType() {
        return new AncillaryBizsType();
    }

    /**
     * Create an instance of {@link PracticeGroupsType }
     * 
     */
    public PracticeGroupsType createPracticeGroupsType() {
        return new PracticeGroupsType();
    }

    /**
     * Create an instance of {@link PgpFaxType }
     * 
     */
    public PgpFaxType createPgpFaxType() {
        return new PgpFaxType();
    }

    /**
     * Create an instance of {@link PrevVanityUrlsType }
     * 
     */
    public PrevVanityUrlsType createPrevVanityUrlsType() {
        return new PrevVanityUrlsType();
    }

    /**
     * Create an instance of {@link SeosType }
     * 
     */
    public SeosType createSeosType() {
        return new SeosType();
    }

    /**
     * Create an instance of {@link AddlPracticeGroupsType }
     * 
     */
    public AddlPracticeGroupsType createAddlPracticeGroupsType() {
        return new AddlPracticeGroupsType();
    }

    /**
     * Create an instance of {@link RepClientsType }
     * 
     */
    public RepClientsType createRepClientsType() {
        return new RepClientsType();
    }

    /**
     * Create an instance of {@link ReferencesType }
     * 
     */
    public ReferencesType createReferencesType() {
        return new ReferencesType();
    }

    /**
     * Create an instance of {@link PgpFirmsiteUrlType }
     * 
     */
    public PgpFirmsiteUrlType createPgpFirmsiteUrlType() {
        return new PgpFirmsiteUrlType();
    }

    /**
     * Create an instance of {@link OtherOfficesType.OtherOffice }
     * 
     */
    public OtherOfficesType.OtherOffice createOtherOfficesTypeOtherOffice() {
        return new OtherOfficesType.OtherOffice();
    }

    /**
     * Create an instance of {@link Profile.TelephonesAnswered }
     * 
     */
    public Profile.TelephonesAnswered createProfileTelephonesAnswered() {
        return new Profile.TelephonesAnswered();
    }

    /**
     * Create an instance of {@link AssocMemberOrgType }
     * 
     */
    public AssocMemberOrgType createAssocMemberOrgType() {
        return new AssocMemberOrgType();
    }

    /**
     * Create an instance of {@link EmailsType }
     * 
     */
    public EmailsType createEmailsType() {
        return new EmailsType();
    }

    /**
     * Create an instance of {@link PracticeGroupAfflsType }
     * 
     */
    public PracticeGroupAfflsType createPracticeGroupAfflsType() {
        return new PracticeGroupAfflsType();
    }

    /**
     * Create an instance of {@link FlBlogUrlType }
     * 
     */
    public FlBlogUrlType createFlBlogUrlType() {
        return new FlBlogUrlType();
    }

    /**
     * Create an instance of {@link GeoPrefsType.GeoPref }
     * 
     */
    public GeoPrefsType.GeoPref createGeoPrefsTypeGeoPref() {
        return new GeoPrefsType.GeoPref();
    }

    /**
     * Create an instance of {@link ImagesType }
     * 
     */
    public ImagesType createImagesType() {
        return new ImagesType();
    }

    /**
     * Create an instance of {@link LanguagesType.Language }
     * 
     */
    public LanguagesType.Language createLanguagesTypeLanguage() {
        return new LanguagesType.Language();
    }

    /**
     * Create an instance of {@link FlVideoTreeGroupType }
     * 
     */
    public FlVideoTreeGroupType createFlVideoTreeGroupType() {
        return new FlVideoTreeGroupType();
    }

    /**
     * Create an instance of {@link OtherAfflsType.OtherAffl }
     * 
     */
    public OtherAfflsType.OtherAffl createOtherAfflsTypeOtherAffl() {
        return new OtherAfflsType.OtherAffl();
    }

    /**
     * Create an instance of {@link AssocDefinedPcsType }
     * 
     */
    public AssocDefinedPcsType createAssocDefinedPcsType() {
        return new AssocDefinedPcsType();
    }

    /**
     * Create an instance of {@link ContactListType }
     * 
     */
    public ContactListType createContactListType() {
        return new ContactListType();
    }

    /**
     * Create an instance of {@link Profile.DeclaredFirmSize }
     * 
     */
    public Profile.DeclaredFirmSize createProfileDeclaredFirmSize() {
        return new Profile.DeclaredFirmSize();
    }

    /**
     * Create an instance of {@link Profile.BarAdmissions }
     * 
     */
    public Profile.BarAdmissions createProfileBarAdmissions() {
        return new Profile.BarAdmissions();
    }

    /**
     * Create an instance of {@link CourtType }
     * 
     */
    public CourtType createCourtType() {
        return new CourtType();
    }

    /**
     * Create an instance of {@link WebsiteAffiliateMatchesType }
     * 
     */
    public WebsiteAffiliateMatchesType createWebsiteAffiliateMatchesType() {
        return new WebsiteAffiliateMatchesType();
    }

    /**
     * Create an instance of {@link PgpInternetUrlsType }
     * 
     */
    public PgpInternetUrlsType createPgpInternetUrlsType() {
        return new PgpInternetUrlsType();
    }

    /**
     * Create an instance of {@link MembersType }
     * 
     */
    public MembersType createMembersType() {
        return new MembersType();
    }

    /**
     * Create an instance of {@link PasType }
     * 
     */
    public PasType createPasType() {
        return new PasType();
    }

    /**
     * Create an instance of {@link PhonesType }
     * 
     */
    public PhonesType createPhonesType() {
        return new PhonesType();
    }

    /**
     * Create an instance of {@link BlogUrlType }
     * 
     */
    public BlogUrlType createBlogUrlType() {
        return new BlogUrlType();
    }

    /**
     * Create an instance of {@link PastPositionsType.PastPosition }
     * 
     */
    public PastPositionsType.PastPosition createPastPositionsTypePastPosition() {
        return new PastPositionsType.PastPosition();
    }

    /**
     * Create an instance of {@link LawPubsType }
     * 
     */
    public LawPubsType createLawPubsType() {
        return new LawPubsType();
    }

    /**
     * Create an instance of {@link MergerAcqsType.MergerAcq }
     * 
     */
    public MergerAcqsType.MergerAcq createMergerAcqsTypeMergerAcq() {
        return new MergerAcqsType.MergerAcq();
    }

    /**
     * Create an instance of {@link LeSchoolHonorsType }
     * 
     */
    public LeSchoolHonorsType createLeSchoolHonorsType() {
        return new LeSchoolHonorsType();
    }

    /**
     * Create an instance of {@link LawInfoContactFormType.LiLanguage }
     * 
     */
    public LawInfoContactFormType.LiLanguage createLawInfoContactFormTypeLiLanguage() {
        return new LawInfoContactFormType.LiLanguage();
    }

    /**
     * Create an instance of {@link FirmsiteUrlType }
     * 
     */
    public FirmsiteUrlType createFirmsiteUrlType() {
        return new FirmsiteUrlType();
    }

    /**
     * Create an instance of {@link FreeTextAopType }
     * 
     */
    public FreeTextAopType createFreeTextAopType() {
        return new FreeTextAopType();
    }

    /**
     * Create an instance of {@link Profile.SpecialInstructions }
     * 
     */
    public Profile.SpecialInstructions createProfileSpecialInstructions() {
        return new Profile.SpecialInstructions();
    }

    /**
     * Create an instance of {@link FaxType }
     * 
     */
    public FaxType createFaxType() {
        return new FaxType();
    }

    /**
     * Create an instance of {@link PgpEmailType }
     * 
     */
    public PgpEmailType createPgpEmailType() {
        return new PgpEmailType();
    }

    /**
     * Create an instance of {@link LawInfoContactFormType }
     * 
     */
    public LawInfoContactFormType createLawInfoContactFormType() {
        return new LawInfoContactFormType();
    }

    /**
     * Create an instance of {@link ChildrenAfflType.ChildAffl }
     * 
     */
    public ChildrenAfflType.ChildAffl createChildrenAfflTypeChildAffl() {
        return new ChildrenAfflType.ChildAffl();
    }

    /**
     * Create an instance of {@link FlVideoTreeGroupType.FlVideoTreeGroupVideo }
     * 
     */
    public FlVideoTreeGroupType.FlVideoTreeGroupVideo createFlVideoTreeGroupTypeFlVideoTreeGroupVideo() {
        return new FlVideoTreeGroupType.FlVideoTreeGroupVideo();
    }

    /**
     * Create an instance of {@link LeMajorsType.LEMajor }
     * 
     */
    public LeMajorsType.LEMajor createLeMajorsTypeLEMajor() {
        return new LeMajorsType.LEMajor();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link PgpPhoneType }
     * 
     */
    public PgpPhoneType createPgpPhoneType() {
        return new PgpPhoneType();
    }

    /**
     * Create an instance of {@link FlVideoType }
     * 
     */
    public FlVideoType createFlVideoType() {
        return new FlVideoType();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link OtherAfflsType }
     * 
     */
    public OtherAfflsType createOtherAfflsType() {
        return new OtherAfflsType();
    }

    /**
     * Create an instance of {@link NleMajorsType.NLEMajor }
     * 
     */
    public NleMajorsType.NLEMajor createNleMajorsTypeNLEMajor() {
        return new NleMajorsType.NLEMajor();
    }

    /**
     * Create an instance of {@link ProfileAuditsType }
     * 
     */
    public ProfileAuditsType createProfileAuditsType() {
        return new ProfileAuditsType();
    }

    /**
     * Create an instance of {@link AddlPersonnelsType.AddlPersonnel }
     * 
     */
    public AddlPersonnelsType.AddlPersonnel createAddlPersonnelsTypeAddlPersonnel() {
        return new AddlPersonnelsType.AddlPersonnel();
    }

    /**
     * Create an instance of {@link ProBonosType }
     * 
     */
    public ProBonosType createProBonosType() {
        return new ProBonosType();
    }

    /**
     * Create an instance of {@link LeMajorsType }
     * 
     */
    public LeMajorsType createLeMajorsType() {
        return new LeMajorsType();
    }

    /**
     * Create an instance of {@link GeoPrefsType }
     * 
     */
    public GeoPrefsType createGeoPrefsType() {
        return new GeoPrefsType();
    }

    /**
     * Create an instance of {@link ProfileAuditsType.ProfileAudit }
     * 
     */
    public ProfileAuditsType.ProfileAudit createProfileAuditsTypeProfileAudit() {
        return new ProfileAuditsType.ProfileAudit();
    }

    /**
     * Create an instance of {@link LanguagesType }
     * 
     */
    public LanguagesType createLanguagesType() {
        return new LanguagesType();
    }

    /**
     * Create an instance of {@link OtherOfficesType }
     * 
     */
    public OtherOfficesType createOtherOfficesType() {
        return new OtherOfficesType();
    }

    /**
     * Create an instance of {@link PositionsType.Position }
     * 
     */
    public PositionsType.Position createPositionsTypePosition() {
        return new PositionsType.Position();
    }

    /**
     * Create an instance of {@link ParentType }
     * 
     */
    public ParentType createParentType() {
        return new ParentType();
    }

    /**
     * Create an instance of {@link SapsType.Sap }
     * 
     */
    public SapsType.Sap createSapsTypeSap() {
        return new SapsType.Sap();
    }

    /**
     * Create an instance of {@link InternetUrlsType }
     * 
     */
    public InternetUrlsType createInternetUrlsType() {
        return new InternetUrlsType();
    }

    /**
     * Create an instance of {@link SpecialtyType }
     * 
     */
    public SpecialtyType createSpecialtyType() {
        return new SpecialtyType();
    }

    /**
     * Create an instance of {@link ProBonosType.ProBono }
     * 
     */
    public ProBonosType.ProBono createProBonosTypeProBono() {
        return new ProBonosType.ProBono();
    }

    /**
     * Create an instance of {@link MemOfAssocsType.MemAssoc }
     * 
     */
    public MemOfAssocsType.MemAssoc createMemOfAssocsTypeMemAssoc() {
        return new MemOfAssocsType.MemAssoc();
    }

    /**
     * Create an instance of {@link NleMajorsType }
     * 
     */
    public NleMajorsType createNleMajorsType() {
        return new NleMajorsType();
    }

    /**
     * Create an instance of {@link PgpPhonesType }
     * 
     */
    public PgpPhonesType createPgpPhonesType() {
        return new PgpPhonesType();
    }

    /**
     * Create an instance of {@link IndividualType.YearJoinedFirm }
     * 
     */
    public IndividualType.YearJoinedFirm createIndividualTypeYearJoinedFirm() {
        return new IndividualType.YearJoinedFirm();
    }

    /**
     * Create an instance of {@link PwPAsType.PWPA }
     * 
     */
    public PwPAsType.PWPA createPwPAsTypePWPA() {
        return new PwPAsType.PWPA();
    }

    /**
     * Create an instance of {@link IndNameType }
     * 
     */
    public IndNameType createIndNameType() {
        return new IndNameType();
    }

    /**
     * Create an instance of {@link SapsType }
     * 
     */
    public SapsType createSapsType() {
        return new SapsType();
    }

    /**
     * Create an instance of {@link FlBlogUrlsType }
     * 
     */
    public FlBlogUrlsType createFlBlogUrlsType() {
        return new FlBlogUrlsType();
    }

    /**
     * Create an instance of {@link LsAddressType }
     * 
     */
    public LsAddressType createLsAddressType() {
        return new LsAddressType();
    }

    /**
     * Create an instance of {@link PracticeGroupAfflsType.PracticeGroupAffl }
     * 
     */
    public PracticeGroupAfflsType.PracticeGroupAffl createPracticeGroupAfflsTypePracticeGroupAffl() {
        return new PracticeGroupAfflsType.PracticeGroupAffl();
    }

    /**
     * Create an instance of {@link FlBlogPAsType }
     * 
     */
    public FlBlogPAsType createFlBlogPAsType() {
        return new FlBlogPAsType();
    }

    /**
     * Create an instance of {@link Profile.Consultations }
     * 
     */
    public Profile.Consultations createProfileConsultations() {
        return new Profile.Consultations();
    }

    /**
     * Create an instance of {@link ClerkHistoriesType.ClerkHistory }
     * 
     */
    public ClerkHistoriesType.ClerkHistory createClerkHistoriesTypeClerkHistory() {
        return new ClerkHistoriesType.ClerkHistory();
    }

    /**
     * Create an instance of {@link Profile.StaffedChat }
     * 
     */
    public Profile.StaffedChat createProfileStaffedChat() {
        return new Profile.StaffedChat();
    }

    /**
     * Create an instance of {@link Profile.SuperLawyersData }
     * 
     */
    public Profile.SuperLawyersData createProfileSuperLawyersData() {
        return new Profile.SuperLawyersData();
    }

    /**
     * Create an instance of {@link LawInfoContactFormType.LiCallTimes }
     * 
     */
    public LawInfoContactFormType.LiCallTimes createLawInfoContactFormTypeLiCallTimes() {
        return new LawInfoContactFormType.LiCallTimes();
    }

    /**
     * Create an instance of {@link PasType.PA }
     * 
     */
    public PasType.PA createPasTypePA() {
        return new PasType.PA();
    }

    /**
     * Create an instance of {@link RepCasesType }
     * 
     */
    public RepCasesType createRepCasesType() {
        return new RepCasesType();
    }

    /**
     * Create an instance of {@link AddlPersonnelsType }
     * 
     */
    public AddlPersonnelsType createAddlPersonnelsType() {
        return new AddlPersonnelsType();
    }

    /**
     * Create an instance of {@link BlogUrlsType }
     * 
     */
    public BlogUrlsType createBlogUrlsType() {
        return new BlogUrlsType();
    }

    /**
     * Create an instance of {@link Profile.Specialties }
     * 
     */
    public Profile.Specialties createProfileSpecialties() {
        return new Profile.Specialties();
    }

    /**
     * Create an instance of {@link LawInfoContactFormType.LiAfterHours }
     * 
     */
    public LawInfoContactFormType.LiAfterHours createLawInfoContactFormTypeLiAfterHours() {
        return new LawInfoContactFormType.LiAfterHours();
    }

    /**
     * Create an instance of {@link OoStateType }
     * 
     */
    public OoStateType createOoStateType() {
        return new OoStateType();
    }

    /**
     * Create an instance of {@link InternetUrlType }
     * 
     */
    public InternetUrlType createInternetUrlType() {
        return new InternetUrlType();
    }

    /**
     * Create an instance of {@link PrevNamesType.PrevName }
     * 
     */
    public PrevNamesType.PrevName createPrevNamesTypePrevName() {
        return new PrevNamesType.PrevName();
    }

    /**
     * Create an instance of {@link OrganizationType }
     * 
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link PublishedWorksType }
     * 
     */
    public PublishedWorksType createPublishedWorksType() {
        return new PublishedWorksType();
    }

    /**
     * Create an instance of {@link MemOfAssocsType }
     * 
     */
    public MemOfAssocsType createMemOfAssocsType() {
        return new MemOfAssocsType();
    }

    /**
     * Create an instance of {@link ImagesType.PhotoPath }
     * 
     */
    public ImagesType.PhotoPath createImagesTypePhotoPath() {
        return new ImagesType.PhotoPath();
    }

    /**
     * Create an instance of {@link MergerAcqsType }
     * 
     */
    public MergerAcqsType createMergerAcqsType() {
        return new MergerAcqsType();
    }

    /**
     * Create an instance of {@link FaxesType }
     * 
     */
    public FaxesType createFaxesType() {
        return new FaxesType();
    }

    /**
     * Create an instance of {@link NleSchoolHonorsType }
     * 
     */
    public NleSchoolHonorsType createNleSchoolHonorsType() {
        return new NleSchoolHonorsType();
    }

    /**
     * Create an instance of {@link Profile.EmplPrefs }
     * 
     */
    public Profile.EmplPrefs createProfileEmplPrefs() {
        return new Profile.EmplPrefs();
    }

    /**
     * Create an instance of {@link CountryType }
     * 
     */
    public CountryType createCountryType() {
        return new CountryType();
    }

    /**
     * Create an instance of {@link IndividualType.Born }
     * 
     */
    public IndividualType.Born createIndividualTypeBorn() {
        return new IndividualType.Born();
    }

    /**
     * Create an instance of {@link LawInfoContactFormType.LiVoice }
     * 
     */
    public LawInfoContactFormType.LiVoice createLawInfoContactFormTypeLiVoice() {
        return new LawInfoContactFormType.LiVoice();
    }

    /**
     * Create an instance of {@link LawInfoContactFormType.LiBehavior }
     * 
     */
    public LawInfoContactFormType.LiBehavior createLawInfoContactFormTypeLiBehavior() {
        return new LawInfoContactFormType.LiBehavior();
    }

    /**
     * Create an instance of {@link ClerkHistoriesType }
     * 
     */
    public ClerkHistoriesType createClerkHistoriesType() {
        return new ClerkHistoriesType();
    }

    /**
     * Create an instance of {@link IndividualType }
     * 
     */
    public IndividualType createIndividualType() {
        return new IndividualType();
    }

    /**
     * Create an instance of {@link SeosType.SEO }
     * 
     */
    public SeosType.SEO createSeosTypeSEO() {
        return new SeosType.SEO();
    }

    /**
     * Create an instance of {@link SeosType.SEO.VanityURLAddr }
     * 
     */
    public SeosType.SEO.VanityURLAddr createSeosTypeSEOVanityURLAddr() {
        return new SeosType.SEO.VanityURLAddr();
    }

    /**
     * Create an instance of {@link MembersType.ClerkHistory }
     * 
     */
    public MembersType.ClerkHistory createMembersTypeClerkHistory() {
        return new MembersType.ClerkHistory();
    }

    /**
     * Create an instance of {@link PastPositionsType }
     * 
     */
    public PastPositionsType createPastPositionsType() {
        return new PastPositionsType();
    }

    /**
     * Create an instance of {@link PublishedWorksType.PublishedWork }
     * 
     */
    public PublishedWorksType.PublishedWork createPublishedWorksTypePublishedWork() {
        return new PublishedWorksType.PublishedWork();
    }

    /**
     * Create an instance of {@link FlBlogPAsType.FlBlogPa }
     * 
     */
    public FlBlogPAsType.FlBlogPa createFlBlogPAsTypeFlBlogPa() {
        return new FlBlogPAsType.FlBlogPa();
    }

    /**
     * Create an instance of {@link PgpFaxesType }
     * 
     */
    public PgpFaxesType createPgpFaxesType() {
        return new PgpFaxesType();
    }

    /**
     * Create an instance of {@link FirmsitePAsType.FirmsitePa }
     * 
     */
    public FirmsitePAsType.FirmsitePa createFirmsitePAsTypeFirmsitePa() {
        return new FirmsitePAsType.FirmsitePa();
    }

    /**
     * Create an instance of {@link LawInfoContactFormType.LiMode }
     * 
     */
    public LawInfoContactFormType.LiMode createLawInfoContactFormTypeLiMode() {
        return new LawInfoContactFormType.LiMode();
    }

    /**
     * Create an instance of {@link FlVideosType }
     * 
     */
    public FlVideosType createFlVideosType() {
        return new FlVideosType();
    }

    /**
     * Create an instance of {@link ProfilePropertiesType.SapCustomerNum }
     * 
     */
    public ProfilePropertiesType.SapCustomerNum createProfilePropertiesTypeSapCustomerNum() {
        return new ProfilePropertiesType.SapCustomerNum();
    }

    /**
     * Create an instance of {@link OoAddrType }
     * 
     */
    public OoAddrType createOoAddrType() {
        return new OoAddrType();
    }

    /**
     * Create an instance of {@link AssocDefinedPcsType.AssocDefinedPC }
     * 
     */
    public AssocDefinedPcsType.AssocDefinedPC createAssocDefinedPcsTypeAssocDefinedPC() {
        return new AssocDefinedPcsType.AssocDefinedPC();
    }

    /**
     * Create an instance of {@link FratSorosType.FratSoro }
     * 
     */
    public FratSorosType.FratSoro createFratSorosTypeFratSoro() {
        return new FratSorosType.FratSoro();
    }

    /**
     * Create an instance of {@link LawPubsType.LawPub }
     * 
     */
    public LawPubsType.LawPub createLawPubsTypeLawPub() {
        return new LawPubsType.LawPub();
    }

    /**
     * Create an instance of {@link MemberAssocPcsType }
     * 
     */
    public MemberAssocPcsType createMemberAssocPcsType() {
        return new MemberAssocPcsType();
    }

    /**
     * Create an instance of {@link UltimateParentNameType }
     * 
     */
    public UltimateParentNameType createUltimateParentNameType() {
        return new UltimateParentNameType();
    }

    /**
     * Create an instance of {@link LeType }
     * 
     */
    public LeType createLeType() {
        return new LeType();
    }

    /**
     * Create an instance of {@link HonorsType.Honor }
     * 
     */
    public HonorsType.Honor createHonorsTypeHonor() {
        return new HonorsType.Honor();
    }

    /**
     * Create an instance of {@link RepCasesType.Case }
     * 
     */
    public RepCasesType.Case createRepCasesTypeCase() {
        return new RepCasesType.Case();
    }

    /**
     * Create an instance of {@link LsCountryType }
     * 
     */
    public LsCountryType createLsCountryType() {
        return new LsCountryType();
    }

    /**
     * Create an instance of {@link EducationType }
     * 
     */
    public EducationType createEducationType() {
        return new EducationType();
    }

    /**
     * Create an instance of {@link Profile.EmplPrefs.EmplPref }
     * 
     */
    public Profile.EmplPrefs.EmplPref createProfileEmplPrefsEmplPref() {
        return new Profile.EmplPrefs.EmplPref();
    }

    /**
     * Create an instance of {@link ExpertiseAreasType.ExpertiseArea }
     * 
     */
    public ExpertiseAreasType.ExpertiseArea createExpertiseAreasTypeExpertiseArea() {
        return new ExpertiseAreasType.ExpertiseArea();
    }

    /**
     * Create an instance of {@link Profile.OfficeHours }
     * 
     */
    public Profile.OfficeHours createProfileOfficeHours() {
        return new Profile.OfficeHours();
    }

    /**
     * Create an instance of {@link PgpEmailsType }
     * 
     */
    public PgpEmailsType createPgpEmailsType() {
        return new PgpEmailsType();
    }

    /**
     * Create an instance of {@link Profile.FreeTextAOPs }
     * 
     */
    public Profile.FreeTextAOPs createProfileFreeTextAOPs() {
        return new Profile.FreeTextAOPs();
    }

    /**
     * Create an instance of {@link PositionsType }
     * 
     */
    public PositionsType createPositionsType() {
        return new PositionsType();
    }

    /**
     * Create an instance of {@link ChildrenAfflType }
     * 
     */
    public ChildrenAfflType createChildrenAfflType() {
        return new ChildrenAfflType();
    }

    /**
     * Create an instance of {@link ExpertiseAreasType }
     * 
     */
    public ExpertiseAreasType createExpertiseAreasType() {
        return new ExpertiseAreasType();
    }

    /**
     * Create an instance of {@link FratSorosType }
     * 
     */
    public FratSorosType createFratSorosType() {
        return new FratSorosType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PA_prac_pct", scope = PasType.PA.class)
    public JAXBElement<Integer> createPasTypePAPAPracPct(Integer value) {
        return new JAXBElement<Integer>(_PasTypePAPAPracPct_QNAME, Integer.class, PasType.PA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PA_topical_code", scope = PasType.PA.class)
    public JAXBElement<BigInteger> createPasTypePAPATopicalCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_PasTypePAPATopicalCode_QNAME, BigInteger.class, PasType.PA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PA_desc", scope = PasType.PA.class)
    public JAXBElement<String> createPasTypePAPADesc(String value) {
        return new JAXBElement<String>(_PasTypePAPADesc_QNAME, String.class, PasType.PA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PA_practice_code", scope = PasType.PA.class)
    public JAXBElement<BigInteger> createPasTypePAPAPracticeCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_PasTypePAPAPracticeCode_QNAME, BigInteger.class, PasType.PA.class, value);
    }

}
