//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ooCountryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ooCountryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="oo_country_name" type="{}string30"/>
 *         &lt;element name="oo_country_code" type="{}countryCodeType"/>
 *         &lt;element name="oo_ovd_country_name" type="{}string30" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ooCountryType", propOrder = {
    "ooCountryName",
    "ooCountryCode",
    "ooOvdCountryName"
})
public class OoCountryType {

    @XmlElement(name = "oo_country_name", required = true)
    protected String ooCountryName;
    @XmlElement(name = "oo_country_code")
    protected int ooCountryCode;
    @XmlElement(name = "oo_ovd_country_name")
    protected String ooOvdCountryName;

    /**
     * Gets the value of the ooCountryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOoCountryName() {
        return ooCountryName;
    }

    /**
     * Sets the value of the ooCountryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOoCountryName(String value) {
        this.ooCountryName = value;
    }

    /**
     * Gets the value of the ooCountryCode property.
     * 
     */
    public int getOoCountryCode() {
        return ooCountryCode;
    }

    /**
     * Sets the value of the ooCountryCode property.
     * 
     */
    public void setOoCountryCode(int value) {
        this.ooCountryCode = value;
    }

    /**
     * Gets the value of the ooOvdCountryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOoOvdCountryName() {
        return ooOvdCountryName;
    }

    /**
     * Sets the value of the ooOvdCountryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOoOvdCountryName(String value) {
        this.ooOvdCountryName = value;
    }

}
