//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ooStateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ooStateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="oo_state_name" type="{}string25" minOccurs="0"/>
 *         &lt;element name="oo_state_abbr" type="{}string3" minOccurs="0"/>
 *         &lt;element name="oo_state_code" type="{}stateCodeType" minOccurs="0"/>
 *         &lt;element name="oo_ovd_state_name" type="{}string25" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ooStateType", propOrder = {
    "ooStateName",
    "ooStateAbbr",
    "ooStateCode",
    "ooOvdStateName"
})
public class OoStateType {

    @XmlElement(name = "oo_state_name")
    protected String ooStateName;
    @XmlElement(name = "oo_state_abbr")
    protected String ooStateAbbr;
    @XmlElement(name = "oo_state_code")
    protected Integer ooStateCode;
    @XmlElement(name = "oo_ovd_state_name")
    protected String ooOvdStateName;

    /**
     * Gets the value of the ooStateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOoStateName() {
        return ooStateName;
    }

    /**
     * Sets the value of the ooStateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOoStateName(String value) {
        this.ooStateName = value;
    }

    /**
     * Gets the value of the ooStateAbbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOoStateAbbr() {
        return ooStateAbbr;
    }

    /**
     * Sets the value of the ooStateAbbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOoStateAbbr(String value) {
        this.ooStateAbbr = value;
    }

    /**
     * Gets the value of the ooStateCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOoStateCode() {
        return ooStateCode;
    }

    /**
     * Sets the value of the ooStateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOoStateCode(Integer value) {
        this.ooStateCode = value;
    }

    /**
     * Gets the value of the ooOvdStateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOoOvdStateName() {
        return ooOvdStateName;
    }

    /**
     * Sets the value of the ooOvdStateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOoOvdStateName(String value) {
        this.ooOvdStateName = value;
    }

}
