//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for orgType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="orgType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ASS"/>
 *     &lt;enumeration value="CPY"/>
 *     &lt;enumeration value="CRT"/>
 *     &lt;enumeration value="GOV"/>
 *     &lt;enumeration value="LEE"/>
 *     &lt;enumeration value="LEV"/>
 *     &lt;enumeration value="LFM"/>
 *     &lt;enumeration value="NON"/>
 *     &lt;enumeration value="SCH"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum OrgType {

    ASS,
    CPY,
    CRT,
    GOV,
    LEE,
    LEV,
    LFM,
    NON,
    SCH;

    public String value() {
        return name();
    }

    public static OrgType fromValue(String v) {
        return valueOf(v);
    }

}
