//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for pasType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pasType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PA" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;sequence>
 *                     &lt;element name="PA_desc" type="{}string80"/>
 *                     &lt;element name="PA_practice_code" type="{}digit5"/>
 *                     &lt;element name="PA_prac_pct" type="{}percentageType" minOccurs="0"/>
 *                     &lt;element name="PA_topical_code" type="{}digit3" maxOccurs="unbounded"/>
 *                   &lt;/sequence>
 *                   &lt;sequence>
 *                     &lt;element name="PA_practice_code" type="{}digit5"/>
 *                     &lt;element name="PA_desc" type="{}string80"/>
 *                     &lt;element name="PA_prac_pct" type="{}percentageType" minOccurs="0"/>
 *                     &lt;element name="PA_topical_code" type="{}digit3" maxOccurs="unbounded"/>
 *                   &lt;/sequence>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="pie_chart_display_flag" type="{}yesNoFlag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pasType", propOrder = {
    "pa"
})
public class PasType {

    @XmlElement(name = "PA", required = true)
    protected List<PA> pa;
    @XmlAttribute(name = "pie_chart_display_flag")
    protected String pieChartDisplayFlag;

    /**
     * Gets the value of the pa property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pa property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPA().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PasType.PA }
     *
     *
     */
    public List<PA> getPA() {
        if (pa == null) {
            pa = new ArrayList<PA>();
        }
        return this.pa;
    }

    /**
     * Gets the value of the pieChartDisplayFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPieChartDisplayFlag() {
        return pieChartDisplayFlag;
    }

    /**
     * Sets the value of the pieChartDisplayFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPieChartDisplayFlag(String value) {
        this.pieChartDisplayFlag = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;sequence>
     *           &lt;element name="PA_desc" type="{}string80"/>
     *           &lt;element name="PA_practice_code" type="{}digit5"/>
     *           &lt;element name="PA_prac_pct" type="{}percentageType" minOccurs="0"/>
     *           &lt;element name="PA_topical_code" type="{}digit3" maxOccurs="unbounded"/>
     *         &lt;/sequence>
     *         &lt;sequence>
     *           &lt;element name="PA_practice_code" type="{}digit5"/>
     *           &lt;element name="PA_desc" type="{}string80"/>
     *           &lt;element name="PA_prac_pct" type="{}percentageType" minOccurs="0"/>
     *           &lt;element name="PA_topical_code" type="{}digit3" maxOccurs="unbounded"/>
     *         &lt;/sequence>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class PA {

        @XmlElementRefs({
            @XmlElementRef(name = "PA_prac_pct", type = JAXBElement.class),
            @XmlElementRef(name = "PA_practice_code", type = JAXBElement.class),
            @XmlElementRef(name = "PA_desc", type = JAXBElement.class),
            @XmlElementRef(name = "PA_topical_code", type = JAXBElement.class)
        })
        protected List<JAXBElement<? extends Serializable>> content;

        /**
         * Gets the rest of the content model. 
         * 
         * <p>
         * You are getting this "catch-all" property because of the following reason: 
         * The field name "PAPracticeCode" is used by two different parts of a schema. See: 
         * line 20 of http://xstore.findlaw.com/xsd/PAs.xsd
         * line 15 of http://xstore.findlaw.com/xsd/PAs.xsd
         * <p>
         * To get rid of this property, apply a property customization to one 
         * of both of the following declarations to change their names: 
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
         * {@link JAXBElement }{@code <}{@link Integer }{@code >}
         * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * 
         * 
         */
        public List<JAXBElement<? extends Serializable>> getContent() {
            if (content == null) {
                content = new ArrayList<JAXBElement<? extends Serializable>>();
            }
            return this.content;
        }

    }

}
