//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for pgpEmailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pgpEmailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pgp_email_addr" type="{}emailAddrType" minOccurs="0"/>
 *         &lt;element name="pgp_email_notes" type="{}string70" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="inherited_pgp_email" type="{}yesNoFlag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pgpEmailType", propOrder = {
    "pgpEmailAddr",
    "pgpEmailNotes"
})
public class PgpEmailType {

    @XmlElement(name = "pgp_email_addr")
    protected String pgpEmailAddr;
    @XmlElement(name = "pgp_email_notes")
    protected String pgpEmailNotes;
    @XmlAttribute(name = "inherited_pgp_email")
    protected String inheritedPgpEmail;

    /**
     * Gets the value of the pgpEmailAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPgpEmailAddr() {
        return pgpEmailAddr;
    }

    /**
     * Sets the value of the pgpEmailAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPgpEmailAddr(String value) {
        this.pgpEmailAddr = value;
    }

    /**
     * Gets the value of the pgpEmailNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPgpEmailNotes() {
        return pgpEmailNotes;
    }

    /**
     * Sets the value of the pgpEmailNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPgpEmailNotes(String value) {
        this.pgpEmailNotes = value;
    }

    /**
     * Gets the value of the inheritedPgpEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInheritedPgpEmail() {
        return inheritedPgpEmail;
    }

    /**
     * Sets the value of the inheritedPgpEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInheritedPgpEmail(String value) {
        this.inheritedPgpEmail = value;
    }

}
