//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for pgpPhoneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pgpPhoneType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pgp_phone_number" type="{}string100" minOccurs="0"/>
 *         &lt;element name="pgp_phone_notes" type="{}string70" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="inherited_pgp_phone" type="{}yesNoFlag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pgpPhoneType", propOrder = {
    "pgpPhoneNumber",
    "pgpPhoneNotes"
})
public class PgpPhoneType {

    @XmlElement(name = "pgp_phone_number")
    protected String pgpPhoneNumber;
    @XmlElement(name = "pgp_phone_notes")
    protected String pgpPhoneNotes;
    @XmlAttribute(name = "inherited_pgp_phone")
    protected String inheritedPgpPhone;

    /**
     * Gets the value of the pgpPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPgpPhoneNumber() {
        return pgpPhoneNumber;
    }

    /**
     * Sets the value of the pgpPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPgpPhoneNumber(String value) {
        this.pgpPhoneNumber = value;
    }

    /**
     * Gets the value of the pgpPhoneNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPgpPhoneNotes() {
        return pgpPhoneNotes;
    }

    /**
     * Sets the value of the pgpPhoneNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPgpPhoneNotes(String value) {
        this.pgpPhoneNotes = value;
    }

    /**
     * Gets the value of the inheritedPgpPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInheritedPgpPhone() {
        return inheritedPgpPhone;
    }

    /**
     * Sets the value of the inheritedPgpPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInheritedPgpPhone(String value) {
        this.inheritedPgpPhone = value;
    }

}
