//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for prevVanityUrlsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="prevVanityUrlsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Prev_Vanity_URL" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="prev_vanity_URL_addr" type="{}string400" minOccurs="0"/>
 *                   &lt;element name="prev_vanity_URL_chg_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "prevVanityUrlsType", propOrder = {
    "prevVanityURL"
})
public class PrevVanityUrlsType {

    @XmlElement(name = "Prev_Vanity_URL")
    protected List<PrevVanityURL> prevVanityURL;

    /**
     * Gets the value of the prevVanityURL property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prevVanityURL property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrevVanityURL().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrevVanityUrlsType.PrevVanityURL }
     *
     *
     */
    public List<PrevVanityURL> getPrevVanityURL() {
        if (prevVanityURL == null) {
            prevVanityURL = new ArrayList<PrevVanityURL>();
        }
        return this.prevVanityURL;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="prev_vanity_URL_addr" type="{}string400" minOccurs="0"/>
     *         &lt;element name="prev_vanity_URL_chg_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "prevVanityURLAddr",
        "prevVanityURLChgDate"
    })
    public static class PrevVanityURL {

        @XmlElement(name = "prev_vanity_URL_addr")
        protected String prevVanityURLAddr;
        @XmlElement(name = "prev_vanity_URL_chg_date")
        protected String prevVanityURLChgDate;

        /**
         * Gets the value of the prevVanityURLAddr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrevVanityURLAddr() {
            return prevVanityURLAddr;
        }

        /**
         * Sets the value of the prevVanityURLAddr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrevVanityURLAddr(String value) {
            this.prevVanityURLAddr = value;
        }

        /**
         * Gets the value of the prevVanityURLChgDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrevVanityURLChgDate() {
            return prevVanityURLChgDate;
        }

        /**
         * Sets the value of the prevVanityURLChgDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrevVanityURLChgDate(String value) {
            this.prevVanityURLChgDate = value;
        }

    }

}
