//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for prevNamesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="prevNamesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PrevName" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="prev_name" type="{}string141"/>
 *                   &lt;element name="change_date" type="{}zeroOrMoreDigits" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "prevNamesType", propOrder = {
    "prevName"
})
public class PrevNamesType {

    @XmlElement(name = "PrevName", required = true)
    protected List<PrevName> prevName;

    /**
     * Gets the value of the prevName property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prevName property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrevName().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrevNamesType.PrevName }
     *
     *
     */
    public List<PrevName> getPrevName() {
        if (prevName == null) {
            prevName = new ArrayList<PrevName>();
        }
        return this.prevName;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="prev_name" type="{}string141"/>
     *         &lt;element name="change_date" type="{}zeroOrMoreDigits" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "prevName",
        "changeDate"
    })
    public static class PrevName {

        @XmlElement(name = "prev_name", required = true)
        protected String prevName;
        @XmlElement(name = "change_date")
        protected String changeDate;

        /**
         * Gets the value of the prevName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrevName() {
            return prevName;
        }

        /**
         * Sets the value of the prevName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrevName(String value) {
            this.prevName = value;
        }

        /**
         * Gets the value of the changeDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChangeDate() {
            return changeDate;
        }

        /**
         * Sets the value of the changeDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChangeDate(String value) {
            this.changeDate = value;
        }

    }

}
