//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for profileAuditsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="profileAuditsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProfileAudit" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AU_audit_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AU_audit_source" type="{}auAuditSourceType"/>
 *                   &lt;element name="AU_reason_code" type="{}auReasonCodeType"/>
 *                   &lt;element name="AU_user_id" type="{}string64"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "profileAuditsType", propOrder = {
    "profileAudit"
})
public class ProfileAuditsType {

    @XmlElement(name = "ProfileAudit", required = true)
    protected List<ProfileAudit> profileAudit;

    /**
     * Gets the value of the profileAudit property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the profileAudit property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfileAudit().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfileAuditsType.ProfileAudit }
     *
     *
     */
    public List<ProfileAudit> getProfileAudit() {
        if (profileAudit == null) {
            profileAudit = new ArrayList<ProfileAudit>();
        }
        return this.profileAudit;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AU_audit_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AU_audit_source" type="{}auAuditSourceType"/>
     *         &lt;element name="AU_reason_code" type="{}auReasonCodeType"/>
     *         &lt;element name="AU_user_id" type="{}string64"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "auAuditDate",
        "auAuditSource",
        "auReasonCode",
        "auUserId"
    })
    public static class ProfileAudit {

        @XmlElement(name = "AU_audit_date", required = true)
        protected String auAuditDate;
        @XmlElement(name = "AU_audit_source", required = true)
        protected String auAuditSource;
        @XmlElement(name = "AU_reason_code", required = true)
        protected String auReasonCode;
        @XmlElement(name = "AU_user_id", required = true)
        protected String auUserId;

        /**
         * Gets the value of the auAuditDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAUAuditDate() {
            return auAuditDate;
        }

        /**
         * Sets the value of the auAuditDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAUAuditDate(String value) {
            this.auAuditDate = value;
        }

        /**
         * Gets the value of the auAuditSource property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAUAuditSource() {
            return auAuditSource;
        }

        /**
         * Sets the value of the auAuditSource property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAUAuditSource(String value) {
            this.auAuditSource = value;
        }

        /**
         * Gets the value of the auReasonCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAUReasonCode() {
            return auReasonCode;
        }

        /**
         * Sets the value of the auReasonCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAUReasonCode(String value) {
            this.auReasonCode = value;
        }

        /**
         * Gets the value of the auUserId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAUUserId() {
            return auUserId;
        }

        /**
         * Sets the value of the auUserId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAUUserId(String value) {
            this.auUserId = value;
        }

    }

}
