//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.19 at 12:29:35 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProfileProperties" type="{}profilePropertiesType"/>
 *         &lt;element name="Date_Published_To_Xml" type="{}allDigitsDateTime"/>
 *         &lt;choice>
 *           &lt;element name="Individual" type="{}individualType"/>
 *           &lt;element name="Organization" type="{}organizationType"/>
 *         &lt;/choice>
 *         &lt;element name="Ultimate_Parent_Name" type="{}ultimateParentNameType" minOccurs="0"/>
 *         &lt;element name="Parent" type="{}parentType" minOccurs="0"/>
 *         &lt;element name="Address" type="{}addressType"/>
 *         &lt;element name="LS_Address" type="{}lsAddressType" minOccurs="0"/>
 *         &lt;element name="Images" type="{}imagesType" minOccurs="0"/>
 *         &lt;element name="lawinfo_contact_form" type="{}lawInfoContactFormType"/>
 *         &lt;element name="Phones" type="{}phonesType" minOccurs="0"/>
 *         &lt;element name="Emails" type="{}emailsType" minOccurs="0"/>
 *         &lt;element name="Faxes" type="{}faxesType" minOccurs="0"/>
 *         &lt;element name="Firmsite_URLs" type="{}firmsiteUrlsType" minOccurs="0"/>
 *         &lt;element name="Internet_URLs" type="{}internetUrlsType" minOccurs="0"/>
 *         &lt;element name="FL_Blog_URLs" type="{}flBlogUrlsType" minOccurs="0"/>
 *         &lt;element name="Blog_URLs" type="{}blogUrlsType" minOccurs="0"/>
 *         &lt;element name="FL_Videos" type="{}flVideosType" minOccurs="0"/>
 *         &lt;element name="OfficeHours" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="inherited_oh" type="{}yesNoFlag" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Consultations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="free_consultation_flag" type="{}yesNoFlag" />
 *                 &lt;attribute name="inherited_co" type="{}yesNoFlag" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PaymentTypes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="accept_credit_cards_flag" type="{}yesNoFlag" />
 *                 &lt;attribute name="inherited_pt" type="{}yesNoFlag" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DeclaredFirmSize" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="inherited_ds" type="{}yesNoFlag" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StaffedChat" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="app_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="inherited_sc" type="{}yesNoFlag" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PaymentPlansAccepted" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="inherited_ppa" type="{}yesNoFlag" />
 *                 &lt;attribute name="payment_plans_accepted_flag" type="{}yesNoFlag" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TelephonesAnswered" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="telephones_answered_flag" type="{}yesNoFlag" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Appointments" type="{}string50"/>
 *         &lt;element name="SuperLawyersData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="on_directory_result" type="{}yesNoFlag" />
 *                 &lt;attribute name="on_profile_view" type="{}yesNoFlag" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="NarrativeText" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="inherited_nt" type="{}yesNoFlag" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SpecialInstructions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="inherited_si" type="{}yesNoFlag" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Positions" type="{}positionsType" minOccurs="0"/>
 *         &lt;element name="FreeTextAOPs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FreeTextAOP" type="{}freeTextAopType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="pie_chart_display_flag" type="{}yesNoFlag" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Litigation" type="{}percentageType" minOccurs="0"/>
 *         &lt;element name="Specialties" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Specialty" type="{}specialtyType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BarAdmissions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BarAdmission" type="{}barAdmissionType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GeoPrefs" type="{}geoPrefsType" minOccurs="0"/>
 *         &lt;element name="EmplPrefs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EmplPref" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="empl_pref" type="{}string40"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="empl_pref_code" type="{}emplPrefCodeType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Education" type="{}educationType" minOccurs="0"/>
 *         &lt;element name="PublishedWorks" type="{}publishedWorksType" minOccurs="0"/>
 *         &lt;element name="RepCases" type="{}repCasesType" minOccurs="0"/>
 *         &lt;element name="RepClients" type="{}repClientsType" minOccurs="0"/>
 *         &lt;element name="References" type="{}referencesType" minOccurs="0"/>
 *         &lt;element name="ClassesSeminars" type="{}classesSeminarsType" minOccurs="0"/>
 *         &lt;element name="Honors" type="{}honorsType" minOccurs="0"/>
 *         &lt;element name="OtherAffls" type="{}otherAfflsType" minOccurs="0"/>
 *         &lt;element name="PastPositions" type="{}pastPositionsType" minOccurs="0"/>
 *         &lt;element name="ProBonos" type="{}proBonosType" minOccurs="0"/>
 *         &lt;element name="PrevNames" type="{}prevNamesType" minOccurs="0"/>
 *         &lt;element name="MergerAcqs" type="{}mergerAcqsType" minOccurs="0"/>
 *         &lt;element name="AncillaryBizs" type="{}ancillaryBizsType" minOccurs="0"/>
 *         &lt;element name="Court" type="{}courtType" minOccurs="0"/>
 *         &lt;element name="ChildrenAffl" type="{}childrenAfflType" minOccurs="0"/>
 *         &lt;element name="AddlPersonnels" type="{}addlPersonnelsType" minOccurs="0"/>
 *         &lt;element name="OtherOffices" type="{}otherOfficesType" minOccurs="0"/>
 *         &lt;element name="Languages" type="{}languagesType" minOccurs="0"/>
 *         &lt;element name="FratSoros" type="{}fratSorosType" minOccurs="0"/>
 *         &lt;element name="PAs" type="{}pasType" minOccurs="0"/>
 *         &lt;element name="ExpertiseAreas" type="{}expertiseAreasType" minOccurs="0"/>
 *         &lt;element name="RegionsServed" type="{}regionsServedType" minOccurs="0"/>
 *         &lt;element name="ContactList" type="{}contactListType" minOccurs="0"/>
 *         &lt;element name="ClerkHistories" type="{}clerkHistoriesType" minOccurs="0"/>
 *         &lt;element name="Members" type="{}membersType" minOccurs="0"/>
 *         &lt;element name="memOfAssocs" type="{}memOfAssocsType" minOccurs="0"/>
 *         &lt;element name="Assoc_Defined_PCs" type="{}assocDefinedPcsType" minOccurs="0"/>
 *         &lt;element name="ProfileAudits" type="{}profileAuditsType" minOccurs="0"/>
 *         &lt;element name="Saps" type="{}sapsType" minOccurs="0"/>
 *         &lt;element name="PracticeGroupAffls" type="{}practiceGroupAfflsType" minOccurs="0"/>
 *         &lt;element name="PracticeGroups" type="{}practiceGroupsType" minOccurs="0"/>
 *         &lt;element name="AddlPracticeGroups" type="{}addlPracticeGroupsType" minOccurs="0"/>
 *         &lt;element name="Website_Affiliate_Matches" type="{}websiteAffiliateMatchesType" minOccurs="0"/>
 *         &lt;element name="SEOs" type="{}seosType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "profileProperties",
    "datePublishedToXml",
    "individual",
    "organization",
    "ultimateParentName",
    "parent",
    "address",
    "lsAddress",
    "images",
    "lawinfoContactForm",
    "phones",
    "emails",
    "faxes",
    "firmsiteURLs",
    "internetURLs",
    "flBlogURLs",
    "blogURLs",
    "flVideos",
    "officeHours",
    "consultations",
    "paymentTypes",
    "declaredFirmSize",
    "staffedChat",
    "paymentPlansAccepted",
    "telephonesAnswered",
    "appointments",
    "superLawyersData",
    "narrativeText",
    "specialInstructions",
    "positions",
    "freeTextAOPs",
    "litigation",
    "specialties",
    "barAdmissions",
    "geoPrefs",
    "emplPrefs",
    "education",
    "publishedWorks",
    "repCases",
    "repClients",
    "references",
    "classesSeminars",
    "honors",
    "otherAffls",
    "pastPositions",
    "proBonos",
    "prevNames",
    "mergerAcqs",
    "ancillaryBizs",
    "court",
    "childrenAffl",
    "addlPersonnels",
    "otherOffices",
    "languages",
    "fratSoros",
    "pAs",
    "expertiseAreas",
    "regionsServed",
    "contactList",
    "clerkHistories",
    "members",
    "memOfAssocs",
    "assocDefinedPCs",
    "profileAudits",
    "saps",
    "practiceGroupAffls",
    "practiceGroups",
    "addlPracticeGroups",
    "websiteAffiliateMatches",
    "seOs"
})
@XmlRootElement(name = "Profile")
public class Profile {

    @XmlElement(name = "ProfileProperties", required = true)
    protected ProfilePropertiesType profileProperties;
    @XmlElement(name = "Date_Published_To_Xml", required = true)
    protected String datePublishedToXml;
    @XmlElement(name = "Individual")
    protected IndividualType individual;
    @XmlElement(name = "Organization")
    protected OrganizationType organization;
    @XmlElement(name = "Ultimate_Parent_Name")
    protected UltimateParentNameType ultimateParentName;
    @XmlElement(name = "Parent")
    protected ParentType parent;
    @XmlElement(name = "Address", required = true)
    protected AddressType address;
    @XmlElement(name = "LS_Address")
    protected LsAddressType lsAddress;
    @XmlElement(name = "Images")
    protected ImagesType images;
    @XmlElement(name = "lawinfo_contact_form", required = true)
    protected LawInfoContactFormType lawinfoContactForm;
    @XmlElement(name = "Phones")
    protected PhonesType phones;
    @XmlElement(name = "Emails")
    protected EmailsType emails;
    @XmlElement(name = "Faxes")
    protected FaxesType faxes;
    @XmlElement(name = "Firmsite_URLs")
    protected FirmsiteUrlsType firmsiteURLs;
    @XmlElement(name = "Internet_URLs")
    protected InternetUrlsType internetURLs;
    @XmlElement(name = "FL_Blog_URLs")
    protected FlBlogUrlsType flBlogURLs;
    @XmlElement(name = "Blog_URLs")
    protected BlogUrlsType blogURLs;
    @XmlElement(name = "FL_Videos")
    protected FlVideosType flVideos;
    @XmlElement(name = "OfficeHours")
    protected Profile.OfficeHours officeHours;
    @XmlElement(name = "Consultations")
    protected Profile.Consultations consultations;
    @XmlElement(name = "PaymentTypes")
    protected Profile.PaymentTypes paymentTypes;
    @XmlElement(name = "DeclaredFirmSize")
    protected Profile.DeclaredFirmSize declaredFirmSize;
    @XmlElement(name = "StaffedChat")
    protected Profile.StaffedChat staffedChat;
    @XmlElement(name = "PaymentPlansAccepted")
    protected Profile.PaymentPlansAccepted paymentPlansAccepted;
    @XmlElement(name = "TelephonesAnswered")
    protected Profile.TelephonesAnswered telephonesAnswered;
    @XmlElement(name = "Appointments", required = true)
    protected String appointments;
    @XmlElement(name = "SuperLawyersData")
    protected Profile.SuperLawyersData superLawyersData;
    @XmlElement(name = "NarrativeText")
    protected Profile.NarrativeText narrativeText;
    @XmlElement(name = "SpecialInstructions")
    protected Profile.SpecialInstructions specialInstructions;
    @XmlElement(name = "Positions")
    protected PositionsType positions;
    @XmlElement(name = "FreeTextAOPs")
    protected Profile.FreeTextAOPs freeTextAOPs;
    @XmlElement(name = "Litigation")
    protected Integer litigation;
    @XmlElement(name = "Specialties")
    protected Profile.Specialties specialties;
    @XmlElement(name = "BarAdmissions")
    protected Profile.BarAdmissions barAdmissions;
    @XmlElement(name = "GeoPrefs")
    protected GeoPrefsType geoPrefs;
    @XmlElement(name = "EmplPrefs")
    protected Profile.EmplPrefs emplPrefs;
    @XmlElement(name = "Education")
    protected EducationType education;
    @XmlElement(name = "PublishedWorks")
    protected PublishedWorksType publishedWorks;
    @XmlElement(name = "RepCases")
    protected RepCasesType repCases;
    @XmlElement(name = "RepClients")
    protected RepClientsType repClients;
    @XmlElement(name = "References")
    protected ReferencesType references;
    @XmlElement(name = "ClassesSeminars")
    protected ClassesSeminarsType classesSeminars;
    @XmlElement(name = "Honors")
    protected HonorsType honors;
    @XmlElement(name = "OtherAffls")
    protected OtherAfflsType otherAffls;
    @XmlElement(name = "PastPositions")
    protected PastPositionsType pastPositions;
    @XmlElement(name = "ProBonos")
    protected ProBonosType proBonos;
    @XmlElement(name = "PrevNames")
    protected PrevNamesType prevNames;
    @XmlElement(name = "MergerAcqs")
    protected MergerAcqsType mergerAcqs;
    @XmlElement(name = "AncillaryBizs")
    protected AncillaryBizsType ancillaryBizs;
    @XmlElement(name = "Court")
    protected CourtType court;
    @XmlElement(name = "ChildrenAffl")
    protected ChildrenAfflType childrenAffl;
    @XmlElement(name = "AddlPersonnels")
    protected AddlPersonnelsType addlPersonnels;
    @XmlElement(name = "OtherOffices")
    protected OtherOfficesType otherOffices;
    @XmlElement(name = "Languages")
    protected LanguagesType languages;
    @XmlElement(name = "FratSoros")
    protected FratSorosType fratSoros;
    @XmlElement(name = "PAs")
    protected PasType pAs;
    @XmlElement(name = "ExpertiseAreas")
    protected ExpertiseAreasType expertiseAreas;
    @XmlElement(name = "RegionsServed")
    protected RegionsServedType regionsServed;
    @XmlElement(name = "ContactList")
    protected ContactListType contactList;
    @XmlElement(name = "ClerkHistories")
    protected ClerkHistoriesType clerkHistories;
    @XmlElement(name = "Members")
    protected MembersType members;
    protected MemOfAssocsType memOfAssocs;
    @XmlElement(name = "Assoc_Defined_PCs")
    protected AssocDefinedPcsType assocDefinedPCs;
    @XmlElement(name = "ProfileAudits")
    protected ProfileAuditsType profileAudits;
    @XmlElement(name = "Saps")
    protected SapsType saps;
    @XmlElement(name = "PracticeGroupAffls")
    protected PracticeGroupAfflsType practiceGroupAffls;
    @XmlElement(name = "PracticeGroups")
    protected PracticeGroupsType practiceGroups;
    @XmlElement(name = "AddlPracticeGroups")
    protected AddlPracticeGroupsType addlPracticeGroups;
    @XmlElement(name = "Website_Affiliate_Matches")
    protected WebsiteAffiliateMatchesType websiteAffiliateMatches;
    @XmlElement(name = "SEOs")
    protected SeosType seOs;

    /**
     * Gets the value of the profileProperties property.
     *
     * @return
     *     possible object is
     *     {@link ProfilePropertiesType }
     *
     */
    public ProfilePropertiesType getProfileProperties() {
        return profileProperties;
    }

    /**
     * Sets the value of the profileProperties property.
     *
     * @param value
     *     allowed object is
     *     {@link ProfilePropertiesType }
     *
     */
    public void setProfileProperties(ProfilePropertiesType value) {
        this.profileProperties = value;
    }

    /**
     * Gets the value of the datePublishedToXml property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDatePublishedToXml() {
        return datePublishedToXml;
    }

    /**
     * Sets the value of the datePublishedToXml property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDatePublishedToXml(String value) {
        this.datePublishedToXml = value;
    }

    /**
     * Gets the value of the individual property.
     *
     * @return
     *     possible object is
     *     {@link IndividualType }
     *
     */
    public IndividualType getIndividual() {
        return individual;
    }

    /**
     * Sets the value of the individual property.
     *
     * @param value
     *     allowed object is
     *     {@link IndividualType }
     *
     */
    public void setIndividual(IndividualType value) {
        this.individual = value;
    }

    /**
     * Gets the value of the organization property.
     *
     * @return
     *     possible object is
     *     {@link OrganizationType }
     *
     */
    public OrganizationType getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     *
     * @param value
     *     allowed object is
     *     {@link OrganizationType }
     *
     */
    public void setOrganization(OrganizationType value) {
        this.organization = value;
    }

    /**
     * Gets the value of the ultimateParentName property.
     *
     * @return
     *     possible object is
     *     {@link UltimateParentNameType }
     *
     */
    public UltimateParentNameType getUltimateParentName() {
        return ultimateParentName;
    }

    /**
     * Sets the value of the ultimateParentName property.
     *
     * @param value
     *     allowed object is
     *     {@link UltimateParentNameType }
     *
     */
    public void setUltimateParentName(UltimateParentNameType value) {
        this.ultimateParentName = value;
    }

    /**
     * Gets the value of the parent property.
     *
     * @return
     *     possible object is
     *     {@link ParentType }
     *
     */
    public ParentType getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     *
     * @param value
     *     allowed object is
     *     {@link ParentType }
     *
     */
    public void setParent(ParentType value) {
        this.parent = value;
    }

    /**
     * Gets the value of the address property.
     *
     * @return
     *     possible object is
     *     {@link AddressType }
     *
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     *
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the lsAddress property.
     *
     * @return
     *     possible object is
     *     {@link LsAddressType }
     *
     */
    public LsAddressType getLSAddress() {
        return lsAddress;
    }

    /**
     * Sets the value of the lsAddress property.
     *
     * @param value
     *     allowed object is
     *     {@link LsAddressType }
     *
     */
    public void setLSAddress(LsAddressType value) {
        this.lsAddress = value;
    }

    /**
     * Gets the value of the images property.
     *
     * @return
     *     possible object is
     *     {@link ImagesType }
     *
     */
    public ImagesType getImages() {
        return images;
    }

    /**
     * Sets the value of the images property.
     *
     * @param value
     *     allowed object is
     *     {@link ImagesType }
     *
     */
    public void setImages(ImagesType value) {
        this.images = value;
    }

    /**
     * Gets the value of the lawinfoContactForm property.
     *
     * @return
     *     possible object is
     *     {@link LawInfoContactFormType }
     *
     */
    public LawInfoContactFormType getLawinfoContactForm() {
        return lawinfoContactForm;
    }

    /**
     * Sets the value of the lawinfoContactForm property.
     *
     * @param value
     *     allowed object is
     *     {@link LawInfoContactFormType }
     *
     */
    public void setLawinfoContactForm(LawInfoContactFormType value) {
        this.lawinfoContactForm = value;
    }

    /**
     * Gets the value of the phones property.
     *
     * @return
     *     possible object is
     *     {@link PhonesType }
     *
     */
    public PhonesType getPhones() {
        return phones;
    }

    /**
     * Sets the value of the phones property.
     *
     * @param value
     *     allowed object is
     *     {@link PhonesType }
     *
     */
    public void setPhones(PhonesType value) {
        this.phones = value;
    }

    /**
     * Gets the value of the emails property.
     *
     * @return
     *     possible object is
     *     {@link EmailsType }
     *
     */
    public EmailsType getEmails() {
        return emails;
    }

    /**
     * Sets the value of the emails property.
     *
     * @param value
     *     allowed object is
     *     {@link EmailsType }
     *
     */
    public void setEmails(EmailsType value) {
        this.emails = value;
    }

    /**
     * Gets the value of the faxes property.
     *
     * @return
     *     possible object is
     *     {@link FaxesType }
     *
     */
    public FaxesType getFaxes() {
        return faxes;
    }

    /**
     * Sets the value of the faxes property.
     *
     * @param value
     *     allowed object is
     *     {@link FaxesType }
     *
     */
    public void setFaxes(FaxesType value) {
        this.faxes = value;
    }

    /**
     * Gets the value of the firmsiteURLs property.
     *
     * @return
     *     possible object is
     *     {@link FirmsiteUrlsType }
     *
     */
    public FirmsiteUrlsType getFirmsiteURLs() {
        return firmsiteURLs;
    }

    /**
     * Sets the value of the firmsiteURLs property.
     *
     * @param value
     *     allowed object is
     *     {@link FirmsiteUrlsType }
     *
     */
    public void setFirmsiteURLs(FirmsiteUrlsType value) {
        this.firmsiteURLs = value;
    }

    /**
     * Gets the value of the internetURLs property.
     *
     * @return
     *     possible object is
     *     {@link InternetUrlsType }
     *
     */
    public InternetUrlsType getInternetURLs() {
        return internetURLs;
    }

    /**
     * Sets the value of the internetURLs property.
     *
     * @param value
     *     allowed object is
     *     {@link InternetUrlsType }
     *
     */
    public void setInternetURLs(InternetUrlsType value) {
        this.internetURLs = value;
    }

    /**
     * Gets the value of the flBlogURLs property.
     *
     * @return
     *     possible object is
     *     {@link FlBlogUrlsType }
     *
     */
    public FlBlogUrlsType getFLBlogURLs() {
        return flBlogURLs;
    }

    /**
     * Sets the value of the flBlogURLs property.
     *
     * @param value
     *     allowed object is
     *     {@link FlBlogUrlsType }
     *
     */
    public void setFLBlogURLs(FlBlogUrlsType value) {
        this.flBlogURLs = value;
    }

    /**
     * Gets the value of the blogURLs property.
     *
     * @return
     *     possible object is
     *     {@link BlogUrlsType }
     *
     */
    public BlogUrlsType getBlogURLs() {
        return blogURLs;
    }

    /**
     * Sets the value of the blogURLs property.
     *
     * @param value
     *     allowed object is
     *     {@link BlogUrlsType }
     *
     */
    public void setBlogURLs(BlogUrlsType value) {
        this.blogURLs = value;
    }

    /**
     * Gets the value of the flVideos property.
     *
     * @return
     *     possible object is
     *     {@link FlVideosType }
     *
     */
    public FlVideosType getFLVideos() {
        return flVideos;
    }

    /**
     * Sets the value of the flVideos property.
     *
     * @param value
     *     allowed object is
     *     {@link FlVideosType }
     *
     */
    public void setFLVideos(FlVideosType value) {
        this.flVideos = value;
    }

    /**
     * Gets the value of the officeHours property.
     *
     * @return
     *     possible object is
     *     {@link Profile.OfficeHours }
     *
     */
    public Profile.OfficeHours getOfficeHours() {
        return officeHours;
    }

    /**
     * Sets the value of the officeHours property.
     *
     * @param value
     *     allowed object is
     *     {@link Profile.OfficeHours }
     *
     */
    public void setOfficeHours(Profile.OfficeHours value) {
        this.officeHours = value;
    }

    /**
     * Gets the value of the consultations property.
     *
     * @return
     *     possible object is
     *     {@link Profile.Consultations }
     *
     */
    public Profile.Consultations getConsultations() {
        return consultations;
    }

    /**
     * Sets the value of the consultations property.
     *
     * @param value
     *     allowed object is
     *     {@link Profile.Consultations }
     *
     */
    public void setConsultations(Profile.Consultations value) {
        this.consultations = value;
    }

    /**
     * Gets the value of the paymentTypes property.
     *
     * @return
     *     possible object is
     *     {@link Profile.PaymentTypes }
     *
     */
    public Profile.PaymentTypes getPaymentTypes() {
        return paymentTypes;
    }

    /**
     * Sets the value of the paymentTypes property.
     *
     * @param value
     *     allowed object is
     *     {@link Profile.PaymentTypes }
     *
     */
    public void setPaymentTypes(Profile.PaymentTypes value) {
        this.paymentTypes = value;
    }

    /**
     * Gets the value of the declaredFirmSize property.
     *
     * @return
     *     possible object is
     *     {@link Profile.DeclaredFirmSize }
     *
     */
    public Profile.DeclaredFirmSize getDeclaredFirmSize() {
        return declaredFirmSize;
    }

    /**
     * Sets the value of the declaredFirmSize property.
     *
     * @param value
     *     allowed object is
     *     {@link Profile.DeclaredFirmSize }
     *
     */
    public void setDeclaredFirmSize(Profile.DeclaredFirmSize value) {
        this.declaredFirmSize = value;
    }

    /**
     * Gets the value of the staffedChat property.
     *
     * @return
     *     possible object is
     *     {@link Profile.StaffedChat }
     *
     */
    public Profile.StaffedChat getStaffedChat() {
        return staffedChat;
    }

    /**
     * Sets the value of the staffedChat property.
     *
     * @param value
     *     allowed object is
     *     {@link Profile.StaffedChat }
     *
     */
    public void setStaffedChat(Profile.StaffedChat value) {
        this.staffedChat = value;
    }

    /**
     * Gets the value of the paymentPlansAccepted property.
     *
     * @return
     *     possible object is
     *     {@link Profile.PaymentPlansAccepted }
     *
     */
    public Profile.PaymentPlansAccepted getPaymentPlansAccepted() {
        return paymentPlansAccepted;
    }

    /**
     * Sets the value of the paymentPlansAccepted property.
     *
     * @param value
     *     allowed object is
     *     {@link Profile.PaymentPlansAccepted }
     *
     */
    public void setPaymentPlansAccepted(Profile.PaymentPlansAccepted value) {
        this.paymentPlansAccepted = value;
    }

    /**
     * Gets the value of the telephonesAnswered property.
     *
     * @return
     *     possible object is
     *     {@link Profile.TelephonesAnswered }
     *
     */
    public Profile.TelephonesAnswered getTelephonesAnswered() {
        return telephonesAnswered;
    }

    /**
     * Sets the value of the telephonesAnswered property.
     *
     * @param value
     *     allowed object is
     *     {@link Profile.TelephonesAnswered }
     *
     */
    public void setTelephonesAnswered(Profile.TelephonesAnswered value) {
        this.telephonesAnswered = value;
    }

    /**
     * Gets the value of the appointments property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAppointments() {
        return appointments;
    }

    /**
     * Sets the value of the appointments property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAppointments(String value) {
        this.appointments = value;
    }

    /**
     * Gets the value of the superLawyersData property.
     *
     * @return
     *     possible object is
     *     {@link Profile.SuperLawyersData }
     *
     */
    public Profile.SuperLawyersData getSuperLawyersData() {
        return superLawyersData;
    }

    /**
     * Sets the value of the superLawyersData property.
     *
     * @param value
     *     allowed object is
     *     {@link Profile.SuperLawyersData }
     *
     */
    public void setSuperLawyersData(Profile.SuperLawyersData value) {
        this.superLawyersData = value;
    }

    /**
     * Gets the value of the narrativeText property.
     *
     * @return
     *     possible object is
     *     {@link Profile.NarrativeText }
     *
     */
    public Profile.NarrativeText getNarrativeText() {
        return narrativeText;
    }

    /**
     * Sets the value of the narrativeText property.
     *
     * @param value
     *     allowed object is
     *     {@link Profile.NarrativeText }
     *
     */
    public void setNarrativeText(Profile.NarrativeText value) {
        this.narrativeText = value;
    }

    /**
     * Gets the value of the specialInstructions property.
     *
     * @return
     *     possible object is
     *     {@link Profile.SpecialInstructions }
     *
     */
    public Profile.SpecialInstructions getSpecialInstructions() {
        return specialInstructions;
    }

    /**
     * Sets the value of the specialInstructions property.
     *
     * @param value
     *     allowed object is
     *     {@link Profile.SpecialInstructions }
     *
     */
    public void setSpecialInstructions(Profile.SpecialInstructions value) {
        this.specialInstructions = value;
    }

    /**
     * Gets the value of the positions property.
     *
     * @return
     *     possible object is
     *     {@link PositionsType }
     *
     */
    public PositionsType getPositions() {
        return positions;
    }

    /**
     * Sets the value of the positions property.
     *
     * @param value
     *     allowed object is
     *     {@link PositionsType }
     *
     */
    public void setPositions(PositionsType value) {
        this.positions = value;
    }

    /**
     * Gets the value of the freeTextAOPs property.
     *
     * @return
     *     possible object is
     *     {@link Profile.FreeTextAOPs }
     *
     */
    public Profile.FreeTextAOPs getFreeTextAOPs() {
        return freeTextAOPs;
    }

    /**
     * Sets the value of the freeTextAOPs property.
     *
     * @param value
     *     allowed object is
     *     {@link Profile.FreeTextAOPs }
     *
     */
    public void setFreeTextAOPs(Profile.FreeTextAOPs value) {
        this.freeTextAOPs = value;
    }

    /**
     * Gets the value of the litigation property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getLitigation() {
        return litigation;
    }

    /**
     * Sets the value of the litigation property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setLitigation(Integer value) {
        this.litigation = value;
    }

    /**
     * Gets the value of the specialties property.
     *
     * @return
     *     possible object is
     *     {@link Profile.Specialties }
     *
     */
    public Profile.Specialties getSpecialties() {
        return specialties;
    }

    /**
     * Sets the value of the specialties property.
     *
     * @param value
     *     allowed object is
     *     {@link Profile.Specialties }
     *
     */
    public void setSpecialties(Profile.Specialties value) {
        this.specialties = value;
    }

    /**
     * Gets the value of the barAdmissions property.
     *
     * @return
     *     possible object is
     *     {@link Profile.BarAdmissions }
     *
     */
    public Profile.BarAdmissions getBarAdmissions() {
        return barAdmissions;
    }

    /**
     * Sets the value of the barAdmissions property.
     *
     * @param value
     *     allowed object is
     *     {@link Profile.BarAdmissions }
     *
     */
    public void setBarAdmissions(Profile.BarAdmissions value) {
        this.barAdmissions = value;
    }

    /**
     * Gets the value of the geoPrefs property.
     *
     * @return
     *     possible object is
     *     {@link GeoPrefsType }
     *
     */
    public GeoPrefsType getGeoPrefs() {
        return geoPrefs;
    }

    /**
     * Sets the value of the geoPrefs property.
     *
     * @param value
     *     allowed object is
     *     {@link GeoPrefsType }
     *
     */
    public void setGeoPrefs(GeoPrefsType value) {
        this.geoPrefs = value;
    }

    /**
     * Gets the value of the emplPrefs property.
     *
     * @return
     *     possible object is
     *     {@link Profile.EmplPrefs }
     *
     */
    public Profile.EmplPrefs getEmplPrefs() {
        return emplPrefs;
    }

    /**
     * Sets the value of the emplPrefs property.
     *
     * @param value
     *     allowed object is
     *     {@link Profile.EmplPrefs }
     *
     */
    public void setEmplPrefs(Profile.EmplPrefs value) {
        this.emplPrefs = value;
    }

    /**
     * Gets the value of the education property.
     *
     * @return
     *     possible object is
     *     {@link EducationType }
     *
     */
    public EducationType getEducation() {
        return education;
    }

    /**
     * Sets the value of the education property.
     *
     * @param value
     *     allowed object is
     *     {@link EducationType }
     *
     */
    public void setEducation(EducationType value) {
        this.education = value;
    }

    /**
     * Gets the value of the publishedWorks property.
     *
     * @return
     *     possible object is
     *     {@link PublishedWorksType }
     *
     */
    public PublishedWorksType getPublishedWorks() {
        return publishedWorks;
    }

    /**
     * Sets the value of the publishedWorks property.
     *
     * @param value
     *     allowed object is
     *     {@link PublishedWorksType }
     *
     */
    public void setPublishedWorks(PublishedWorksType value) {
        this.publishedWorks = value;
    }

    /**
     * Gets the value of the repCases property.
     *
     * @return
     *     possible object is
     *     {@link RepCasesType }
     *
     */
    public RepCasesType getRepCases() {
        return repCases;
    }

    /**
     * Sets the value of the repCases property.
     *
     * @param value
     *     allowed object is
     *     {@link RepCasesType }
     *
     */
    public void setRepCases(RepCasesType value) {
        this.repCases = value;
    }

    /**
     * Gets the value of the repClients property.
     *
     * @return
     *     possible object is
     *     {@link RepClientsType }
     *
     */
    public RepClientsType getRepClients() {
        return repClients;
    }

    /**
     * Sets the value of the repClients property.
     *
     * @param value
     *     allowed object is
     *     {@link RepClientsType }
     *
     */
    public void setRepClients(RepClientsType value) {
        this.repClients = value;
    }

    /**
     * Gets the value of the references property.
     *
     * @return
     *     possible object is
     *     {@link ReferencesType }
     *
     */
    public ReferencesType getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     *
     * @param value
     *     allowed object is
     *     {@link ReferencesType }
     *
     */
    public void setReferences(ReferencesType value) {
        this.references = value;
    }

    /**
     * Gets the value of the classesSeminars property.
     *
     * @return
     *     possible object is
     *     {@link ClassesSeminarsType }
     *
     */
    public ClassesSeminarsType getClassesSeminars() {
        return classesSeminars;
    }

    /**
     * Sets the value of the classesSeminars property.
     *
     * @param value
     *     allowed object is
     *     {@link ClassesSeminarsType }
     *
     */
    public void setClassesSeminars(ClassesSeminarsType value) {
        this.classesSeminars = value;
    }

    /**
     * Gets the value of the honors property.
     *
     * @return
     *     possible object is
     *     {@link HonorsType }
     *
     */
    public HonorsType getHonors() {
        return honors;
    }

    /**
     * Sets the value of the honors property.
     *
     * @param value
     *     allowed object is
     *     {@link HonorsType }
     *
     */
    public void setHonors(HonorsType value) {
        this.honors = value;
    }

    /**
     * Gets the value of the otherAffls property.
     *
     * @return
     *     possible object is
     *     {@link OtherAfflsType }
     *
     */
    public OtherAfflsType getOtherAffls() {
        return otherAffls;
    }

    /**
     * Sets the value of the otherAffls property.
     *
     * @param value
     *     allowed object is
     *     {@link OtherAfflsType }
     *
     */
    public void setOtherAffls(OtherAfflsType value) {
        this.otherAffls = value;
    }

    /**
     * Gets the value of the pastPositions property.
     *
     * @return
     *     possible object is
     *     {@link PastPositionsType }
     *
     */
    public PastPositionsType getPastPositions() {
        return pastPositions;
    }

    /**
     * Sets the value of the pastPositions property.
     *
     * @param value
     *     allowed object is
     *     {@link PastPositionsType }
     *
     */
    public void setPastPositions(PastPositionsType value) {
        this.pastPositions = value;
    }

    /**
     * Gets the value of the proBonos property.
     *
     * @return
     *     possible object is
     *     {@link ProBonosType }
     *
     */
    public ProBonosType getProBonos() {
        return proBonos;
    }

    /**
     * Sets the value of the proBonos property.
     *
     * @param value
     *     allowed object is
     *     {@link ProBonosType }
     *
     */
    public void setProBonos(ProBonosType value) {
        this.proBonos = value;
    }

    /**
     * Gets the value of the prevNames property.
     *
     * @return
     *     possible object is
     *     {@link PrevNamesType }
     *
     */
    public PrevNamesType getPrevNames() {
        return prevNames;
    }

    /**
     * Sets the value of the prevNames property.
     *
     * @param value
     *     allowed object is
     *     {@link PrevNamesType }
     *
     */
    public void setPrevNames(PrevNamesType value) {
        this.prevNames = value;
    }

    /**
     * Gets the value of the mergerAcqs property.
     *
     * @return
     *     possible object is
     *     {@link MergerAcqsType }
     *
     */
    public MergerAcqsType getMergerAcqs() {
        return mergerAcqs;
    }

    /**
     * Sets the value of the mergerAcqs property.
     *
     * @param value
     *     allowed object is
     *     {@link MergerAcqsType }
     *
     */
    public void setMergerAcqs(MergerAcqsType value) {
        this.mergerAcqs = value;
    }

    /**
     * Gets the value of the ancillaryBizs property.
     *
     * @return
     *     possible object is
     *     {@link AncillaryBizsType }
     *
     */
    public AncillaryBizsType getAncillaryBizs() {
        return ancillaryBizs;
    }

    /**
     * Sets the value of the ancillaryBizs property.
     *
     * @param value
     *     allowed object is
     *     {@link AncillaryBizsType }
     *
     */
    public void setAncillaryBizs(AncillaryBizsType value) {
        this.ancillaryBizs = value;
    }

    /**
     * Gets the value of the court property.
     *
     * @return
     *     possible object is
     *     {@link CourtType }
     *
     */
    public CourtType getCourt() {
        return court;
    }

    /**
     * Sets the value of the court property.
     *
     * @param value
     *     allowed object is
     *     {@link CourtType }
     *
     */
    public void setCourt(CourtType value) {
        this.court = value;
    }

    /**
     * Gets the value of the childrenAffl property.
     *
     * @return
     *     possible object is
     *     {@link ChildrenAfflType }
     *
     */
    public ChildrenAfflType getChildrenAffl() {
        return childrenAffl;
    }

    /**
     * Sets the value of the childrenAffl property.
     *
     * @param value
     *     allowed object is
     *     {@link ChildrenAfflType }
     *
     */
    public void setChildrenAffl(ChildrenAfflType value) {
        this.childrenAffl = value;
    }

    /**
     * Gets the value of the addlPersonnels property.
     *
     * @return
     *     possible object is
     *     {@link AddlPersonnelsType }
     *
     */
    public AddlPersonnelsType getAddlPersonnels() {
        return addlPersonnels;
    }

    /**
     * Sets the value of the addlPersonnels property.
     *
     * @param value
     *     allowed object is
     *     {@link AddlPersonnelsType }
     *
     */
    public void setAddlPersonnels(AddlPersonnelsType value) {
        this.addlPersonnels = value;
    }

    /**
     * Gets the value of the otherOffices property.
     *
     * @return
     *     possible object is
     *     {@link OtherOfficesType }
     *
     */
    public OtherOfficesType getOtherOffices() {
        return otherOffices;
    }

    /**
     * Sets the value of the otherOffices property.
     *
     * @param value
     *     allowed object is
     *     {@link OtherOfficesType }
     *
     */
    public void setOtherOffices(OtherOfficesType value) {
        this.otherOffices = value;
    }

    /**
     * Gets the value of the languages property.
     *
     * @return
     *     possible object is
     *     {@link LanguagesType }
     *
     */
    public LanguagesType getLanguages() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     *
     * @param value
     *     allowed object is
     *     {@link LanguagesType }
     *
     */
    public void setLanguages(LanguagesType value) {
        this.languages = value;
    }

    /**
     * Gets the value of the fratSoros property.
     *
     * @return
     *     possible object is
     *     {@link FratSorosType }
     *
     */
    public FratSorosType getFratSoros() {
        return fratSoros;
    }

    /**
     * Sets the value of the fratSoros property.
     *
     * @param value
     *     allowed object is
     *     {@link FratSorosType }
     *
     */
    public void setFratSoros(FratSorosType value) {
        this.fratSoros = value;
    }

    /**
     * Gets the value of the pAs property.
     *
     * @return
     *     possible object is
     *     {@link PasType }
     *
     */
    public PasType getPAs() {
        return pAs;
    }

    /**
     * Sets the value of the pAs property.
     *
     * @param value
     *     allowed object is
     *     {@link PasType }
     *
     */
    public void setPAs(PasType value) {
        this.pAs = value;
    }

    /**
     * Gets the value of the expertiseAreas property.
     *
     * @return
     *     possible object is
     *     {@link ExpertiseAreasType }
     *
     */
    public ExpertiseAreasType getExpertiseAreas() {
        return expertiseAreas;
    }

    /**
     * Sets the value of the expertiseAreas property.
     *
     * @param value
     *     allowed object is
     *     {@link ExpertiseAreasType }
     *
     */
    public void setExpertiseAreas(ExpertiseAreasType value) {
        this.expertiseAreas = value;
    }

    /**
     * Gets the value of the regionsServed property.
     *
     * @return
     *     possible object is
     *     {@link RegionsServedType }
     *
     */
    public RegionsServedType getRegionsServed() {
        return regionsServed;
    }

    /**
     * Sets the value of the regionsServed property.
     *
     * @param value
     *     allowed object is
     *     {@link RegionsServedType }
     *
     */
    public void setRegionsServed(RegionsServedType value) {
        this.regionsServed = value;
    }

    /**
     * Gets the value of the contactList property.
     *
     * @return
     *     possible object is
     *     {@link ContactListType }
     *
     */
    public ContactListType getContactList() {
        return contactList;
    }

    /**
     * Sets the value of the contactList property.
     *
     * @param value
     *     allowed object is
     *     {@link ContactListType }
     *
     */
    public void setContactList(ContactListType value) {
        this.contactList = value;
    }

    /**
     * Gets the value of the clerkHistories property.
     *
     * @return
     *     possible object is
     *     {@link ClerkHistoriesType }
     *
     */
    public ClerkHistoriesType getClerkHistories() {
        return clerkHistories;
    }

    /**
     * Sets the value of the clerkHistories property.
     *
     * @param value
     *     allowed object is
     *     {@link ClerkHistoriesType }
     *
     */
    public void setClerkHistories(ClerkHistoriesType value) {
        this.clerkHistories = value;
    }

    /**
     * Gets the value of the members property.
     *
     * @return
     *     possible object is
     *     {@link MembersType }
     *
     */
    public MembersType getMembers() {
        return members;
    }

    /**
     * Sets the value of the members property.
     *
     * @param value
     *     allowed object is
     *     {@link MembersType }
     *
     */
    public void setMembers(MembersType value) {
        this.members = value;
    }

    /**
     * Gets the value of the memOfAssocs property.
     *
     * @return
     *     possible object is
     *     {@link MemOfAssocsType }
     *
     */
    public MemOfAssocsType getMemOfAssocs() {
        return memOfAssocs;
    }

    /**
     * Sets the value of the memOfAssocs property.
     *
     * @param value
     *     allowed object is
     *     {@link MemOfAssocsType }
     *
     */
    public void setMemOfAssocs(MemOfAssocsType value) {
        this.memOfAssocs = value;
    }

    /**
     * Gets the value of the assocDefinedPCs property.
     *
     * @return
     *     possible object is
     *     {@link AssocDefinedPcsType }
     *
     */
    public AssocDefinedPcsType getAssocDefinedPCs() {
        return assocDefinedPCs;
    }

    /**
     * Sets the value of the assocDefinedPCs property.
     *
     * @param value
     *     allowed object is
     *     {@link AssocDefinedPcsType }
     *
     */
    public void setAssocDefinedPCs(AssocDefinedPcsType value) {
        this.assocDefinedPCs = value;
    }

    /**
     * Gets the value of the profileAudits property.
     *
     * @return
     *     possible object is
     *     {@link ProfileAuditsType }
     *
     */
    public ProfileAuditsType getProfileAudits() {
        return profileAudits;
    }

    /**
     * Sets the value of the profileAudits property.
     *
     * @param value
     *     allowed object is
     *     {@link ProfileAuditsType }
     *
     */
    public void setProfileAudits(ProfileAuditsType value) {
        this.profileAudits = value;
    }

    /**
     * Gets the value of the saps property.
     *
     * @return
     *     possible object is
     *     {@link SapsType }
     *
     */
    public SapsType getSaps() {
        return saps;
    }

    /**
     * Sets the value of the saps property.
     *
     * @param value
     *     allowed object is
     *     {@link SapsType }
     *
     */
    public void setSaps(SapsType value) {
        this.saps = value;
    }

    /**
     * Gets the value of the practiceGroupAffls property.
     *
     * @return
     *     possible object is
     *     {@link PracticeGroupAfflsType }
     *
     */
    public PracticeGroupAfflsType getPracticeGroupAffls() {
        return practiceGroupAffls;
    }

    /**
     * Sets the value of the practiceGroupAffls property.
     *
     * @param value
     *     allowed object is
     *     {@link PracticeGroupAfflsType }
     *
     */
    public void setPracticeGroupAffls(PracticeGroupAfflsType value) {
        this.practiceGroupAffls = value;
    }

    /**
     * Gets the value of the practiceGroups property.
     *
     * @return
     *     possible object is
     *     {@link PracticeGroupsType }
     *
     */
    public PracticeGroupsType getPracticeGroups() {
        return practiceGroups;
    }

    /**
     * Sets the value of the practiceGroups property.
     *
     * @param value
     *     allowed object is
     *     {@link PracticeGroupsType }
     *
     */
    public void setPracticeGroups(PracticeGroupsType value) {
        this.practiceGroups = value;
    }

    /**
     * Gets the value of the addlPracticeGroups property.
     *
     * @return
     *     possible object is
     *     {@link AddlPracticeGroupsType }
     *
     */
    public AddlPracticeGroupsType getAddlPracticeGroups() {
        return addlPracticeGroups;
    }

    /**
     * Sets the value of the addlPracticeGroups property.
     *
     * @param value
     *     allowed object is
     *     {@link AddlPracticeGroupsType }
     *
     */
    public void setAddlPracticeGroups(AddlPracticeGroupsType value) {
        this.addlPracticeGroups = value;
    }

    /**
     * Gets the value of the websiteAffiliateMatches property.
     *
     * @return
     *     possible object is
     *     {@link WebsiteAffiliateMatchesType }
     *
     */
    public WebsiteAffiliateMatchesType getWebsiteAffiliateMatches() {
        return websiteAffiliateMatches;
    }

    /**
     * Sets the value of the websiteAffiliateMatches property.
     *
     * @param value
     *     allowed object is
     *     {@link WebsiteAffiliateMatchesType }
     *
     */
    public void setWebsiteAffiliateMatches(WebsiteAffiliateMatchesType value) {
        this.websiteAffiliateMatches = value;
    }

    /**
     * Gets the value of the seOs property.
     *
     * @return
     *     possible object is
     *     {@link SeosType }
     *
     */
    public SeosType getSEOs() {
        return seOs;
    }

    /**
     * Sets the value of the seOs property.
     *
     * @param value
     *     allowed object is
     *     {@link SeosType }
     *
     */
    public void setSEOs(SeosType value) {
        this.seOs = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BarAdmission" type="{}barAdmissionType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "barAdmission"
    })
    public static class BarAdmissions {

        @XmlElement(name = "BarAdmission", required = true)
        protected List<BarAdmissionType> barAdmission;

        /**
         * Gets the value of the barAdmission property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the barAdmission property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBarAdmission().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BarAdmissionType }
         *
         *
         */
        public List<BarAdmissionType> getBarAdmission() {
            if (barAdmission == null) {
                barAdmission = new ArrayList<BarAdmissionType>();
            }
            return this.barAdmission;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="free_consultation_flag" type="{}yesNoFlag" />
     *       &lt;attribute name="inherited_co" type="{}yesNoFlag" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Consultations {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "free_consultation_flag")
        protected String freeConsultationFlag;
        @XmlAttribute(name = "inherited_co")
        protected String inheritedCo;

        /**
         * Gets the value of the value property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the freeConsultationFlag property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getFreeConsultationFlag() {
            return freeConsultationFlag;
        }

        /**
         * Sets the value of the freeConsultationFlag property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setFreeConsultationFlag(String value) {
            this.freeConsultationFlag = value;
        }

        /**
         * Gets the value of the inheritedCo property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getInheritedCo() {
            return inheritedCo;
        }

        /**
         * Sets the value of the inheritedCo property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setInheritedCo(String value) {
            this.inheritedCo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="inherited_ds" type="{}yesNoFlag" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DeclaredFirmSize {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "inherited_ds")
        protected String inheritedDs;

        /**
         * Gets the value of the value property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the inheritedDs property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getInheritedDs() {
            return inheritedDs;
        }

        /**
         * Sets the value of the inheritedDs property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setInheritedDs(String value) {
            this.inheritedDs = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EmplPref" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="empl_pref" type="{}string40"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="empl_pref_code" type="{}emplPrefCodeType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "emplPref"
    })
    public static class EmplPrefs {

        @XmlElement(name = "EmplPref")
        protected List<EmplPref> emplPref;

        /**
         * Gets the value of the emplPref property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the emplPref property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEmplPref().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Profile.EmplPrefs.EmplPref }
         *
         *
         */
        public List<EmplPref> getEmplPref() {
            if (emplPref == null) {
                emplPref = new ArrayList<EmplPref>();
            }
            return this.emplPref;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="empl_pref" type="{}string40"/>
         *       &lt;/sequence>
         *       &lt;attribute name="empl_pref_code" type="{}emplPrefCodeType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "emplPref"
        })
        public static class EmplPref {

            @XmlElement(name = "empl_pref", required = true)
            protected String emplPref;
            @XmlAttribute(name = "empl_pref_code")
            protected EmplPrefCodeType emplPrefCode;

            /**
             * Gets the value of the emplPref property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEmplPref() {
                return emplPref;
            }

            /**
             * Sets the value of the emplPref property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEmplPref(String value) {
                this.emplPref = value;
            }

            /**
             * Gets the value of the emplPrefCode property.
             * 
             * @return
             *     possible object is
             *     {@link EmplPrefCodeType }
             *     
             */
            public EmplPrefCodeType getEmplPrefCode() {
                return emplPrefCode;
            }

            /**
             * Sets the value of the emplPrefCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link EmplPrefCodeType }
             *     
             */
            public void setEmplPrefCode(EmplPrefCodeType value) {
                this.emplPrefCode = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FreeTextAOP" type="{}freeTextAopType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="pie_chart_display_flag" type="{}yesNoFlag" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "freeTextAOP"
    })
    public static class FreeTextAOPs {

        @XmlElement(name = "FreeTextAOP", required = true)
        protected List<FreeTextAopType> freeTextAOP;
        @XmlAttribute(name = "pie_chart_display_flag")
        protected String pieChartDisplayFlag;

        /**
         * Gets the value of the freeTextAOP property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the freeTextAOP property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFreeTextAOP().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FreeTextAopType }
         * 
         * 
         */
        public List<FreeTextAopType> getFreeTextAOP() {
            if (freeTextAOP == null) {
                freeTextAOP = new ArrayList<FreeTextAopType>();
            }
            return this.freeTextAOP;
        }

        /**
         * Gets the value of the pieChartDisplayFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPieChartDisplayFlag() {
            return pieChartDisplayFlag;
        }

        /**
         * Sets the value of the pieChartDisplayFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPieChartDisplayFlag(String value) {
            this.pieChartDisplayFlag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="inherited_nt" type="{}yesNoFlag" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class NarrativeText {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "inherited_nt")
        protected String inheritedNt;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the inheritedNt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInheritedNt() {
            return inheritedNt;
        }

        /**
         * Sets the value of the inheritedNt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInheritedNt(String value) {
            this.inheritedNt = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="inherited_oh" type="{}yesNoFlag" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class OfficeHours {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "inherited_oh")
        protected String inheritedOh;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the inheritedOh property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInheritedOh() {
            return inheritedOh;
        }

        /**
         * Sets the value of the inheritedOh property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInheritedOh(String value) {
            this.inheritedOh = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="inherited_ppa" type="{}yesNoFlag" />
     *       &lt;attribute name="payment_plans_accepted_flag" type="{}yesNoFlag" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PaymentPlansAccepted {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "inherited_ppa")
        protected String inheritedPpa;
        @XmlAttribute(name = "payment_plans_accepted_flag")
        protected String paymentPlansAcceptedFlag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the inheritedPpa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInheritedPpa() {
            return inheritedPpa;
        }

        /**
         * Sets the value of the inheritedPpa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInheritedPpa(String value) {
            this.inheritedPpa = value;
        }

        /**
         * Gets the value of the paymentPlansAcceptedFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaymentPlansAcceptedFlag() {
            return paymentPlansAcceptedFlag;
        }

        /**
         * Sets the value of the paymentPlansAcceptedFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaymentPlansAcceptedFlag(String value) {
            this.paymentPlansAcceptedFlag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="accept_credit_cards_flag" type="{}yesNoFlag" />
     *       &lt;attribute name="inherited_pt" type="{}yesNoFlag" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PaymentTypes {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "accept_credit_cards_flag")
        protected String acceptCreditCardsFlag;
        @XmlAttribute(name = "inherited_pt")
        protected String inheritedPt;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the acceptCreditCardsFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAcceptCreditCardsFlag() {
            return acceptCreditCardsFlag;
        }

        /**
         * Sets the value of the acceptCreditCardsFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAcceptCreditCardsFlag(String value) {
            this.acceptCreditCardsFlag = value;
        }

        /**
         * Gets the value of the inheritedPt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInheritedPt() {
            return inheritedPt;
        }

        /**
         * Sets the value of the inheritedPt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInheritedPt(String value) {
            this.inheritedPt = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="inherited_si" type="{}yesNoFlag" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class SpecialInstructions {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "inherited_si")
        protected String inheritedSi;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the inheritedSi property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInheritedSi() {
            return inheritedSi;
        }

        /**
         * Sets the value of the inheritedSi property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInheritedSi(String value) {
            this.inheritedSi = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Specialty" type="{}specialtyType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "specialty"
    })
    public static class Specialties {

        @XmlElement(name = "Specialty", required = true)
        protected List<SpecialtyType> specialty;

        /**
         * Gets the value of the specialty property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the specialty property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSpecialty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SpecialtyType }
         * 
         * 
         */
        public List<SpecialtyType> getSpecialty() {
            if (specialty == null) {
                specialty = new ArrayList<SpecialtyType>();
            }
            return this.specialty;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="app_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="inherited_sc" type="{}yesNoFlag" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class StaffedChat {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "app_id")
        protected String appId;
        @XmlAttribute(name = "inherited_sc")
        protected String inheritedSc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the appId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAppId() {
            return appId;
        }

        /**
         * Sets the value of the appId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAppId(String value) {
            this.appId = value;
        }

        /**
         * Gets the value of the inheritedSc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInheritedSc() {
            return inheritedSc;
        }

        /**
         * Sets the value of the inheritedSc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInheritedSc(String value) {
            this.inheritedSc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="on_directory_result" type="{}yesNoFlag" />
     *       &lt;attribute name="on_profile_view" type="{}yesNoFlag" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class SuperLawyersData {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "on_directory_result")
        protected String onDirectoryResult;
        @XmlAttribute(name = "on_profile_view")
        protected String onProfileView;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the onDirectoryResult property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOnDirectoryResult() {
            return onDirectoryResult;
        }

        /**
         * Sets the value of the onDirectoryResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOnDirectoryResult(String value) {
            this.onDirectoryResult = value;
        }

        /**
         * Gets the value of the onProfileView property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOnProfileView() {
            return onProfileView;
        }

        /**
         * Sets the value of the onProfileView property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOnProfileView(String value) {
            this.onProfileView = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="telephones_answered_flag" type="{}yesNoFlag" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class TelephonesAnswered {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "telephones_answered_flag")
        protected String telephonesAnsweredFlag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the telephonesAnsweredFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelephonesAnsweredFlag() {
            return telephonesAnsweredFlag;
        }

        /**
         * Sets the value of the telephonesAnsweredFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelephonesAnsweredFlag(String value) {
            this.telephonesAnsweredFlag = value;
        }

    }

}
