//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for pwPAsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pwPAsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PW_PA" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PW_practice_code" type="{}digit5"/>
 *                   &lt;element name="PW_topical_code" type="{}digit3" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="PW_practice_desc" type="{}string80"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pwPAsType", propOrder = {
    "pwpa"
})
public class PwPAsType {

    @XmlElement(name = "PW_PA", required = true)
    protected List<PWPA> pwpa;

    /**
     * Gets the value of the pwpa property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pwpa property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPWPA().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PwPAsType.PWPA }
     *
     *
     */
    public List<PWPA> getPWPA() {
        if (pwpa == null) {
            pwpa = new ArrayList<PWPA>();
        }
        return this.pwpa;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PW_practice_code" type="{}digit5"/>
     *         &lt;element name="PW_topical_code" type="{}digit3" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="PW_practice_desc" type="{}string80"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pwPracticeCode",
        "pwTopicalCode",
        "pwPracticeDesc"
    })
    public static class PWPA {

        @XmlElement(name = "PW_practice_code", required = true)
        protected BigInteger pwPracticeCode;
        @XmlElement(name = "PW_topical_code")
        protected List<BigInteger> pwTopicalCode;
        @XmlElement(name = "PW_practice_desc", required = true)
        protected String pwPracticeDesc;

        /**
         * Gets the value of the pwPracticeCode property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPWPracticeCode() {
            return pwPracticeCode;
        }

        /**
         * Sets the value of the pwPracticeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPWPracticeCode(BigInteger value) {
            this.pwPracticeCode = value;
        }

        /**
         * Gets the value of the pwTopicalCode property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pwTopicalCode property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPWTopicalCode().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BigInteger }
         * 
         * 
         */
        public List<BigInteger> getPWTopicalCode() {
            if (pwTopicalCode == null) {
                pwTopicalCode = new ArrayList<BigInteger>();
            }
            return this.pwTopicalCode;
        }

        /**
         * Gets the value of the pwPracticeDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPWPracticeDesc() {
            return pwPracticeDesc;
        }

        /**
         * Sets the value of the pwPracticeDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPWPracticeDesc(String value) {
            this.pwPracticeDesc = value;
        }

    }

}
