//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ultimateParentNameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ultimateParentNameType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;>orgNameType">
 *       &lt;attribute name="ultimate_parent_firmsite_url" type="{}string100" />
 *       &lt;attribute name="ultimate_parent_guid" use="required" type="{}guidType" />
 *       &lt;attribute name="ultimate_parent_profile_id" use="required" type="{}profileIdType" />
 *       &lt;attribute name="ultimate_parent_wld_id" use="required" type="{}wldIdType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ultimateParentNameType", propOrder = {
    "value"
})
public class UltimateParentNameType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "ultimate_parent_firmsite_url")
    protected String ultimateParentFirmsiteUrl;
    @XmlAttribute(name = "ultimate_parent_guid", required = true)
    protected String ultimateParentGuid;
    @XmlAttribute(name = "ultimate_parent_profile_id", required = true)
    protected int ultimateParentProfileId;
    @XmlAttribute(name = "ultimate_parent_wld_id", required = true)
    protected int ultimateParentWldId;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the ultimateParentFirmsiteUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUltimateParentFirmsiteUrl() {
        return ultimateParentFirmsiteUrl;
    }

    /**
     * Sets the value of the ultimateParentFirmsiteUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUltimateParentFirmsiteUrl(String value) {
        this.ultimateParentFirmsiteUrl = value;
    }

    /**
     * Gets the value of the ultimateParentGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUltimateParentGuid() {
        return ultimateParentGuid;
    }

    /**
     * Sets the value of the ultimateParentGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUltimateParentGuid(String value) {
        this.ultimateParentGuid = value;
    }

    /**
     * Gets the value of the ultimateParentProfileId property.
     * 
     */
    public int getUltimateParentProfileId() {
        return ultimateParentProfileId;
    }

    /**
     * Sets the value of the ultimateParentProfileId property.
     * 
     */
    public void setUltimateParentProfileId(int value) {
        this.ultimateParentProfileId = value;
    }

    /**
     * Gets the value of the ultimateParentWldId property.
     * 
     */
    public int getUltimateParentWldId() {
        return ultimateParentWldId;
    }

    /**
     * Sets the value of the ultimateParentWldId property.
     * 
     */
    public void setUltimateParentWldId(int value) {
        this.ultimateParentWldId = value;
    }

}
