//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 12:01:59 PM PDT 
//


package com.fl.wld.xmlbinding.jaxb.profile;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for websiteAffiliateMatchesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="websiteAffiliateMatchesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Website_Affiliate_Match" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="default_link" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="link_option" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="overwrite_link" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="website_code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "websiteAffiliateMatchesType", propOrder = {
    "websiteAffiliateMatch"
})
public class WebsiteAffiliateMatchesType {

    @XmlElement(name = "Website_Affiliate_Match", required = true)
    protected List<WebsiteAffiliateMatch> websiteAffiliateMatch;

    /**
     * Gets the value of the websiteAffiliateMatch property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the websiteAffiliateMatch property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWebsiteAffiliateMatch().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WebsiteAffiliateMatchesType.WebsiteAffiliateMatch }
     *
     *
     */
    public List<WebsiteAffiliateMatch> getWebsiteAffiliateMatch() {
        if (websiteAffiliateMatch == null) {
            websiteAffiliateMatch = new ArrayList<WebsiteAffiliateMatch>();
        }
        return this.websiteAffiliateMatch;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="default_link" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="link_option" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="overwrite_link" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="website_code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class WebsiteAffiliateMatch {

        @XmlAttribute(name = "default_link")
        protected String defaultLink;
        @XmlAttribute(name = "link_option")
        protected String linkOption;
        @XmlAttribute(name = "overwrite_link")
        protected String overwriteLink;
        @XmlAttribute(name = "website_code")
        protected String websiteCode;

        /**
         * Gets the value of the defaultLink property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefaultLink() {
            return defaultLink;
        }

        /**
         * Sets the value of the defaultLink property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefaultLink(String value) {
            this.defaultLink = value;
        }

        /**
         * Gets the value of the linkOption property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLinkOption() {
            return linkOption;
        }

        /**
         * Sets the value of the linkOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLinkOption(String value) {
            this.linkOption = value;
        }

        /**
         * Gets the value of the overwriteLink property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOverwriteLink() {
            return overwriteLink;
        }

        /**
         * Sets the value of the overwriteLink property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOverwriteLink(String value) {
            this.overwriteLink = value;
        }

        /**
         * Gets the value of the websiteCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWebsiteCode() {
            return websiteCode;
        }

        /**
         * Sets the value of the websiteCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWebsiteCode(String value) {
            this.websiteCode = value;
        }

    }

}
